<?php
/**
 * FastBoundWebModelsApiV1ItemsGetItemCommand
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FastBoundWebModelsApiV1ItemsGetItemCommand Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ItemsGetItemCommand implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FastBound.Web.Models.Api.V1.Items.GetItem+Command';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'item_number' => 'string',
        'do_not_dispose' => 'bool',
        'manufacturer' => 'string',
        'importer' => 'string',
        'model' => 'string',
        'serial' => 'string',
        'type' => 'string',
        'caliber' => 'string',
        'country_of_manufacture' => 'string',
        'barrel_length' => 'double',
        'overall_length' => 'double',
        'total_length' => 'double',
        'location' => 'string',
        'condition' => 'string',
        'location_verified_utc' => '\DateTime',
        'mpn' => 'string',
        'upc' => 'string',
        'sku' => 'string',
        'cost' => 'double',
        'price' => 'double',
        'profit' => 'double',
        'margin' => 'double',
        'acquisition_type' => 'string',
        'acquire_date' => '\DateTime',
        'acquisition_user_email' => 'string',
        'acquire_purchase_order_number' => 'string',
        'acquire_invoice_number' => 'string',
        'acquire_shipment_tracking_number' => 'string',
        'acquire_license' => 'string',
        'acquire_license_name' => 'string',
        'acquire_license_expires' => '\DateTime',
        'acquire_organization' => 'string',
        'acquire_first_name' => 'string',
        'acquire_last_name' => 'string',
        'acquire_address1' => 'string',
        'acquire_address2' => 'string',
        'acquire_city' => 'string',
        'acquire_state' => 'string',
        'acquire_postal' => 'string',
        'acquire_country' => 'string',
        'acquire_phone_number' => 'string',
        'acquire_fax' => 'string',
        'acquire_email_address' => 'string',
        'disposition_type' => 'string',
        'deleted' => 'bool',
        'dispose_date' => '\DateTime',
        'ttsn' => 'string',
        'otsn' => 'string',
        'disposition_user_email' => 'string',
        'dispose_purchase_order_number' => 'string',
        'dispose_invoice_number' => 'string',
        'dispose_shipment_tracking_number' => 'string',
        'dispose_license' => 'string',
        'dispose_license_name' => 'string',
        'dispose_license_expires' => '\DateTime',
        'dispose_organization' => 'string',
        'dispose_first_name' => 'string',
        'dispose_last_name' => 'string',
        'dispose_address1' => 'string',
        'dispose_address2' => 'string',
        'dispose_city' => 'string',
        'dispose_state' => 'string',
        'dispose_postal' => 'string',
        'dispose_country' => 'string',
        'dispose_phone_number' => 'string',
        'dispose_fax' => 'string',
        'dispose_email_address' => 'string',
        'submission_date' => '\DateTime',
        'theft_loss_discovered_date' => '\DateTime',
        'theft_loss_type' => 'string',
        'theft_loss_atf_issued_incident_number' => 'string',
        'theft_loss_police_incident_number' => 'string',
        'destroyed_date' => '\DateTime',
        'destroyed_description' => 'string',
        'destroyed_witness1' => 'string',
        'destroyed_witness2' => 'string',
        'multiple_sale_reports' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsGetItemCommandMultipleSaleReportModel[]',
        'lightspeed_system_id' => 'int',
        'lightspeed_serial_id' => 'int',
        'lightspeed_sale_id' => 'int',
        'id' => 'string',
        'external_id' => 'string',
        'status' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel',
        'disposition_id' => 'string',
        'disposition_external_id' => 'string',
        'create_utc' => '\DateTime',
        'update_utc' => '\DateTime',
        'quick_code_url' => 'string',
        'attachments' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[]',
        'notes' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'item_number' => null,
        'do_not_dispose' => null,
        'manufacturer' => null,
        'importer' => null,
        'model' => null,
        'serial' => null,
        'type' => null,
        'caliber' => null,
        'country_of_manufacture' => null,
        'barrel_length' => 'double',
        'overall_length' => 'double',
        'total_length' => 'double',
        'location' => null,
        'condition' => null,
        'location_verified_utc' => 'date-time',
        'mpn' => null,
        'upc' => null,
        'sku' => null,
        'cost' => 'double',
        'price' => 'double',
        'profit' => 'double',
        'margin' => 'double',
        'acquisition_type' => null,
        'acquire_date' => 'date-time',
        'acquisition_user_email' => null,
        'acquire_purchase_order_number' => null,
        'acquire_invoice_number' => null,
        'acquire_shipment_tracking_number' => null,
        'acquire_license' => null,
        'acquire_license_name' => null,
        'acquire_license_expires' => 'date-time',
        'acquire_organization' => null,
        'acquire_first_name' => null,
        'acquire_last_name' => null,
        'acquire_address1' => null,
        'acquire_address2' => null,
        'acquire_city' => null,
        'acquire_state' => null,
        'acquire_postal' => null,
        'acquire_country' => null,
        'acquire_phone_number' => null,
        'acquire_fax' => null,
        'acquire_email_address' => null,
        'disposition_type' => null,
        'deleted' => null,
        'dispose_date' => 'date-time',
        'ttsn' => null,
        'otsn' => null,
        'disposition_user_email' => null,
        'dispose_purchase_order_number' => null,
        'dispose_invoice_number' => null,
        'dispose_shipment_tracking_number' => null,
        'dispose_license' => null,
        'dispose_license_name' => null,
        'dispose_license_expires' => 'date-time',
        'dispose_organization' => null,
        'dispose_first_name' => null,
        'dispose_last_name' => null,
        'dispose_address1' => null,
        'dispose_address2' => null,
        'dispose_city' => null,
        'dispose_state' => null,
        'dispose_postal' => null,
        'dispose_country' => null,
        'dispose_phone_number' => null,
        'dispose_fax' => null,
        'dispose_email_address' => null,
        'submission_date' => 'date-time',
        'theft_loss_discovered_date' => 'date-time',
        'theft_loss_type' => null,
        'theft_loss_atf_issued_incident_number' => null,
        'theft_loss_police_incident_number' => null,
        'destroyed_date' => 'date-time',
        'destroyed_description' => null,
        'destroyed_witness1' => null,
        'destroyed_witness2' => null,
        'multiple_sale_reports' => null,
        'lightspeed_system_id' => 'int64',
        'lightspeed_serial_id' => 'int64',
        'lightspeed_sale_id' => 'int64',
        'id' => 'uuid',
        'external_id' => null,
        'status' => null,
        'disposition_id' => 'uuid',
        'disposition_external_id' => null,
        'create_utc' => 'date-time',
        'update_utc' => 'date-time',
        'quick_code_url' => null,
        'attachments' => null,
        'notes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_number' => 'itemNumber',
        'do_not_dispose' => 'doNotDispose',
        'manufacturer' => 'manufacturer',
        'importer' => 'importer',
        'model' => 'model',
        'serial' => 'serial',
        'type' => 'type',
        'caliber' => 'caliber',
        'country_of_manufacture' => 'countryOfManufacture',
        'barrel_length' => 'barrelLength',
        'overall_length' => 'overallLength',
        'total_length' => 'totalLength',
        'location' => 'location',
        'condition' => 'condition',
        'location_verified_utc' => 'locationVerifiedUtc',
        'mpn' => 'mpn',
        'upc' => 'upc',
        'sku' => 'sku',
        'cost' => 'cost',
        'price' => 'price',
        'profit' => 'profit',
        'margin' => 'margin',
        'acquisition_type' => 'acquisitionType',
        'acquire_date' => 'acquire_Date',
        'acquisition_user_email' => 'acquisitionUserEmail',
        'acquire_purchase_order_number' => 'acquire_PurchaseOrderNumber',
        'acquire_invoice_number' => 'acquire_InvoiceNumber',
        'acquire_shipment_tracking_number' => 'acquire_ShipmentTrackingNumber',
        'acquire_license' => 'acquire_License',
        'acquire_license_name' => 'acquire_LicenseName',
        'acquire_license_expires' => 'acquire_LicenseExpires',
        'acquire_organization' => 'acquire_Organization',
        'acquire_first_name' => 'acquire_FirstName',
        'acquire_last_name' => 'acquire_LastName',
        'acquire_address1' => 'acquire_Address1',
        'acquire_address2' => 'acquire_Address2',
        'acquire_city' => 'acquire_City',
        'acquire_state' => 'acquire_State',
        'acquire_postal' => 'acquire_Postal',
        'acquire_country' => 'acquire_Country',
        'acquire_phone_number' => 'acquire_PhoneNumber',
        'acquire_fax' => 'acquire_Fax',
        'acquire_email_address' => 'acquire_EmailAddress',
        'disposition_type' => 'dispositionType',
        'deleted' => 'deleted',
        'dispose_date' => 'dispose_Date',
        'ttsn' => 'ttsn',
        'otsn' => 'otsn',
        'disposition_user_email' => 'dispositionUserEmail',
        'dispose_purchase_order_number' => 'dispose_PurchaseOrderNumber',
        'dispose_invoice_number' => 'dispose_InvoiceNumber',
        'dispose_shipment_tracking_number' => 'dispose_ShipmentTrackingNumber',
        'dispose_license' => 'dispose_License',
        'dispose_license_name' => 'dispose_LicenseName',
        'dispose_license_expires' => 'dispose_LicenseExpires',
        'dispose_organization' => 'dispose_Organization',
        'dispose_first_name' => 'dispose_FirstName',
        'dispose_last_name' => 'dispose_LastName',
        'dispose_address1' => 'dispose_Address1',
        'dispose_address2' => 'dispose_Address2',
        'dispose_city' => 'dispose_City',
        'dispose_state' => 'dispose_State',
        'dispose_postal' => 'dispose_Postal',
        'dispose_country' => 'dispose_Country',
        'dispose_phone_number' => 'dispose_PhoneNumber',
        'dispose_fax' => 'dispose_Fax',
        'dispose_email_address' => 'dispose_EmailAddress',
        'submission_date' => 'submissionDate',
        'theft_loss_discovered_date' => 'theftLoss_DiscoveredDate',
        'theft_loss_type' => 'theftLoss_Type',
        'theft_loss_atf_issued_incident_number' => 'theftLoss_ATFIssuedIncidentNumber',
        'theft_loss_police_incident_number' => 'theftLoss_PoliceIncidentNumber',
        'destroyed_date' => 'destroyed_Date',
        'destroyed_description' => 'destroyed_Description',
        'destroyed_witness1' => 'destroyed_Witness1',
        'destroyed_witness2' => 'destroyed_Witness2',
        'multiple_sale_reports' => 'multipleSaleReports',
        'lightspeed_system_id' => 'lightspeedSystemID',
        'lightspeed_serial_id' => 'lightspeedSerialID',
        'lightspeed_sale_id' => 'lightspeedSaleID',
        'id' => 'id',
        'external_id' => 'externalId',
        'status' => 'status',
        'disposition_id' => 'dispositionId',
        'disposition_external_id' => 'dispositionExternalId',
        'create_utc' => 'createUtc',
        'update_utc' => 'updateUtc',
        'quick_code_url' => 'quickCodeUrl',
        'attachments' => 'attachments',
        'notes' => 'notes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_number' => 'setItemNumber',
        'do_not_dispose' => 'setDoNotDispose',
        'manufacturer' => 'setManufacturer',
        'importer' => 'setImporter',
        'model' => 'setModel',
        'serial' => 'setSerial',
        'type' => 'setType',
        'caliber' => 'setCaliber',
        'country_of_manufacture' => 'setCountryOfManufacture',
        'barrel_length' => 'setBarrelLength',
        'overall_length' => 'setOverallLength',
        'total_length' => 'setTotalLength',
        'location' => 'setLocation',
        'condition' => 'setCondition',
        'location_verified_utc' => 'setLocationVerifiedUtc',
        'mpn' => 'setMpn',
        'upc' => 'setUpc',
        'sku' => 'setSku',
        'cost' => 'setCost',
        'price' => 'setPrice',
        'profit' => 'setProfit',
        'margin' => 'setMargin',
        'acquisition_type' => 'setAcquisitionType',
        'acquire_date' => 'setAcquireDate',
        'acquisition_user_email' => 'setAcquisitionUserEmail',
        'acquire_purchase_order_number' => 'setAcquirePurchaseOrderNumber',
        'acquire_invoice_number' => 'setAcquireInvoiceNumber',
        'acquire_shipment_tracking_number' => 'setAcquireShipmentTrackingNumber',
        'acquire_license' => 'setAcquireLicense',
        'acquire_license_name' => 'setAcquireLicenseName',
        'acquire_license_expires' => 'setAcquireLicenseExpires',
        'acquire_organization' => 'setAcquireOrganization',
        'acquire_first_name' => 'setAcquireFirstName',
        'acquire_last_name' => 'setAcquireLastName',
        'acquire_address1' => 'setAcquireAddress1',
        'acquire_address2' => 'setAcquireAddress2',
        'acquire_city' => 'setAcquireCity',
        'acquire_state' => 'setAcquireState',
        'acquire_postal' => 'setAcquirePostal',
        'acquire_country' => 'setAcquireCountry',
        'acquire_phone_number' => 'setAcquirePhoneNumber',
        'acquire_fax' => 'setAcquireFax',
        'acquire_email_address' => 'setAcquireEmailAddress',
        'disposition_type' => 'setDispositionType',
        'deleted' => 'setDeleted',
        'dispose_date' => 'setDisposeDate',
        'ttsn' => 'setTtsn',
        'otsn' => 'setOtsn',
        'disposition_user_email' => 'setDispositionUserEmail',
        'dispose_purchase_order_number' => 'setDisposePurchaseOrderNumber',
        'dispose_invoice_number' => 'setDisposeInvoiceNumber',
        'dispose_shipment_tracking_number' => 'setDisposeShipmentTrackingNumber',
        'dispose_license' => 'setDisposeLicense',
        'dispose_license_name' => 'setDisposeLicenseName',
        'dispose_license_expires' => 'setDisposeLicenseExpires',
        'dispose_organization' => 'setDisposeOrganization',
        'dispose_first_name' => 'setDisposeFirstName',
        'dispose_last_name' => 'setDisposeLastName',
        'dispose_address1' => 'setDisposeAddress1',
        'dispose_address2' => 'setDisposeAddress2',
        'dispose_city' => 'setDisposeCity',
        'dispose_state' => 'setDisposeState',
        'dispose_postal' => 'setDisposePostal',
        'dispose_country' => 'setDisposeCountry',
        'dispose_phone_number' => 'setDisposePhoneNumber',
        'dispose_fax' => 'setDisposeFax',
        'dispose_email_address' => 'setDisposeEmailAddress',
        'submission_date' => 'setSubmissionDate',
        'theft_loss_discovered_date' => 'setTheftLossDiscoveredDate',
        'theft_loss_type' => 'setTheftLossType',
        'theft_loss_atf_issued_incident_number' => 'setTheftLossAtfIssuedIncidentNumber',
        'theft_loss_police_incident_number' => 'setTheftLossPoliceIncidentNumber',
        'destroyed_date' => 'setDestroyedDate',
        'destroyed_description' => 'setDestroyedDescription',
        'destroyed_witness1' => 'setDestroyedWitness1',
        'destroyed_witness2' => 'setDestroyedWitness2',
        'multiple_sale_reports' => 'setMultipleSaleReports',
        'lightspeed_system_id' => 'setLightspeedSystemId',
        'lightspeed_serial_id' => 'setLightspeedSerialId',
        'lightspeed_sale_id' => 'setLightspeedSaleId',
        'id' => 'setId',
        'external_id' => 'setExternalId',
        'status' => 'setStatus',
        'disposition_id' => 'setDispositionId',
        'disposition_external_id' => 'setDispositionExternalId',
        'create_utc' => 'setCreateUtc',
        'update_utc' => 'setUpdateUtc',
        'quick_code_url' => 'setQuickCodeUrl',
        'attachments' => 'setAttachments',
        'notes' => 'setNotes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_number' => 'getItemNumber',
        'do_not_dispose' => 'getDoNotDispose',
        'manufacturer' => 'getManufacturer',
        'importer' => 'getImporter',
        'model' => 'getModel',
        'serial' => 'getSerial',
        'type' => 'getType',
        'caliber' => 'getCaliber',
        'country_of_manufacture' => 'getCountryOfManufacture',
        'barrel_length' => 'getBarrelLength',
        'overall_length' => 'getOverallLength',
        'total_length' => 'getTotalLength',
        'location' => 'getLocation',
        'condition' => 'getCondition',
        'location_verified_utc' => 'getLocationVerifiedUtc',
        'mpn' => 'getMpn',
        'upc' => 'getUpc',
        'sku' => 'getSku',
        'cost' => 'getCost',
        'price' => 'getPrice',
        'profit' => 'getProfit',
        'margin' => 'getMargin',
        'acquisition_type' => 'getAcquisitionType',
        'acquire_date' => 'getAcquireDate',
        'acquisition_user_email' => 'getAcquisitionUserEmail',
        'acquire_purchase_order_number' => 'getAcquirePurchaseOrderNumber',
        'acquire_invoice_number' => 'getAcquireInvoiceNumber',
        'acquire_shipment_tracking_number' => 'getAcquireShipmentTrackingNumber',
        'acquire_license' => 'getAcquireLicense',
        'acquire_license_name' => 'getAcquireLicenseName',
        'acquire_license_expires' => 'getAcquireLicenseExpires',
        'acquire_organization' => 'getAcquireOrganization',
        'acquire_first_name' => 'getAcquireFirstName',
        'acquire_last_name' => 'getAcquireLastName',
        'acquire_address1' => 'getAcquireAddress1',
        'acquire_address2' => 'getAcquireAddress2',
        'acquire_city' => 'getAcquireCity',
        'acquire_state' => 'getAcquireState',
        'acquire_postal' => 'getAcquirePostal',
        'acquire_country' => 'getAcquireCountry',
        'acquire_phone_number' => 'getAcquirePhoneNumber',
        'acquire_fax' => 'getAcquireFax',
        'acquire_email_address' => 'getAcquireEmailAddress',
        'disposition_type' => 'getDispositionType',
        'deleted' => 'getDeleted',
        'dispose_date' => 'getDisposeDate',
        'ttsn' => 'getTtsn',
        'otsn' => 'getOtsn',
        'disposition_user_email' => 'getDispositionUserEmail',
        'dispose_purchase_order_number' => 'getDisposePurchaseOrderNumber',
        'dispose_invoice_number' => 'getDisposeInvoiceNumber',
        'dispose_shipment_tracking_number' => 'getDisposeShipmentTrackingNumber',
        'dispose_license' => 'getDisposeLicense',
        'dispose_license_name' => 'getDisposeLicenseName',
        'dispose_license_expires' => 'getDisposeLicenseExpires',
        'dispose_organization' => 'getDisposeOrganization',
        'dispose_first_name' => 'getDisposeFirstName',
        'dispose_last_name' => 'getDisposeLastName',
        'dispose_address1' => 'getDisposeAddress1',
        'dispose_address2' => 'getDisposeAddress2',
        'dispose_city' => 'getDisposeCity',
        'dispose_state' => 'getDisposeState',
        'dispose_postal' => 'getDisposePostal',
        'dispose_country' => 'getDisposeCountry',
        'dispose_phone_number' => 'getDisposePhoneNumber',
        'dispose_fax' => 'getDisposeFax',
        'dispose_email_address' => 'getDisposeEmailAddress',
        'submission_date' => 'getSubmissionDate',
        'theft_loss_discovered_date' => 'getTheftLossDiscoveredDate',
        'theft_loss_type' => 'getTheftLossType',
        'theft_loss_atf_issued_incident_number' => 'getTheftLossAtfIssuedIncidentNumber',
        'theft_loss_police_incident_number' => 'getTheftLossPoliceIncidentNumber',
        'destroyed_date' => 'getDestroyedDate',
        'destroyed_description' => 'getDestroyedDescription',
        'destroyed_witness1' => 'getDestroyedWitness1',
        'destroyed_witness2' => 'getDestroyedWitness2',
        'multiple_sale_reports' => 'getMultipleSaleReports',
        'lightspeed_system_id' => 'getLightspeedSystemId',
        'lightspeed_serial_id' => 'getLightspeedSerialId',
        'lightspeed_sale_id' => 'getLightspeedSaleId',
        'id' => 'getId',
        'external_id' => 'getExternalId',
        'status' => 'getStatus',
        'disposition_id' => 'getDispositionId',
        'disposition_external_id' => 'getDispositionExternalId',
        'create_utc' => 'getCreateUtc',
        'update_utc' => 'getUpdateUtc',
        'quick_code_url' => 'getQuickCodeUrl',
        'attachments' => 'getAttachments',
        'notes' => 'getNotes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['item_number'] = isset($data['item_number']) ? $data['item_number'] : null;
        $this->container['do_not_dispose'] = isset($data['do_not_dispose']) ? $data['do_not_dispose'] : null;
        $this->container['manufacturer'] = isset($data['manufacturer']) ? $data['manufacturer'] : null;
        $this->container['importer'] = isset($data['importer']) ? $data['importer'] : null;
        $this->container['model'] = isset($data['model']) ? $data['model'] : null;
        $this->container['serial'] = isset($data['serial']) ? $data['serial'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['caliber'] = isset($data['caliber']) ? $data['caliber'] : null;
        $this->container['country_of_manufacture'] = isset($data['country_of_manufacture']) ? $data['country_of_manufacture'] : null;
        $this->container['barrel_length'] = isset($data['barrel_length']) ? $data['barrel_length'] : null;
        $this->container['overall_length'] = isset($data['overall_length']) ? $data['overall_length'] : null;
        $this->container['total_length'] = isset($data['total_length']) ? $data['total_length'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['condition'] = isset($data['condition']) ? $data['condition'] : null;
        $this->container['location_verified_utc'] = isset($data['location_verified_utc']) ? $data['location_verified_utc'] : null;
        $this->container['mpn'] = isset($data['mpn']) ? $data['mpn'] : null;
        $this->container['upc'] = isset($data['upc']) ? $data['upc'] : null;
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['profit'] = isset($data['profit']) ? $data['profit'] : null;
        $this->container['margin'] = isset($data['margin']) ? $data['margin'] : null;
        $this->container['acquisition_type'] = isset($data['acquisition_type']) ? $data['acquisition_type'] : null;
        $this->container['acquire_date'] = isset($data['acquire_date']) ? $data['acquire_date'] : null;
        $this->container['acquisition_user_email'] = isset($data['acquisition_user_email']) ? $data['acquisition_user_email'] : null;
        $this->container['acquire_purchase_order_number'] = isset($data['acquire_purchase_order_number']) ? $data['acquire_purchase_order_number'] : null;
        $this->container['acquire_invoice_number'] = isset($data['acquire_invoice_number']) ? $data['acquire_invoice_number'] : null;
        $this->container['acquire_shipment_tracking_number'] = isset($data['acquire_shipment_tracking_number']) ? $data['acquire_shipment_tracking_number'] : null;
        $this->container['acquire_license'] = isset($data['acquire_license']) ? $data['acquire_license'] : null;
        $this->container['acquire_license_name'] = isset($data['acquire_license_name']) ? $data['acquire_license_name'] : null;
        $this->container['acquire_license_expires'] = isset($data['acquire_license_expires']) ? $data['acquire_license_expires'] : null;
        $this->container['acquire_organization'] = isset($data['acquire_organization']) ? $data['acquire_organization'] : null;
        $this->container['acquire_first_name'] = isset($data['acquire_first_name']) ? $data['acquire_first_name'] : null;
        $this->container['acquire_last_name'] = isset($data['acquire_last_name']) ? $data['acquire_last_name'] : null;
        $this->container['acquire_address1'] = isset($data['acquire_address1']) ? $data['acquire_address1'] : null;
        $this->container['acquire_address2'] = isset($data['acquire_address2']) ? $data['acquire_address2'] : null;
        $this->container['acquire_city'] = isset($data['acquire_city']) ? $data['acquire_city'] : null;
        $this->container['acquire_state'] = isset($data['acquire_state']) ? $data['acquire_state'] : null;
        $this->container['acquire_postal'] = isset($data['acquire_postal']) ? $data['acquire_postal'] : null;
        $this->container['acquire_country'] = isset($data['acquire_country']) ? $data['acquire_country'] : null;
        $this->container['acquire_phone_number'] = isset($data['acquire_phone_number']) ? $data['acquire_phone_number'] : null;
        $this->container['acquire_fax'] = isset($data['acquire_fax']) ? $data['acquire_fax'] : null;
        $this->container['acquire_email_address'] = isset($data['acquire_email_address']) ? $data['acquire_email_address'] : null;
        $this->container['disposition_type'] = isset($data['disposition_type']) ? $data['disposition_type'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
        $this->container['dispose_date'] = isset($data['dispose_date']) ? $data['dispose_date'] : null;
        $this->container['ttsn'] = isset($data['ttsn']) ? $data['ttsn'] : null;
        $this->container['otsn'] = isset($data['otsn']) ? $data['otsn'] : null;
        $this->container['disposition_user_email'] = isset($data['disposition_user_email']) ? $data['disposition_user_email'] : null;
        $this->container['dispose_purchase_order_number'] = isset($data['dispose_purchase_order_number']) ? $data['dispose_purchase_order_number'] : null;
        $this->container['dispose_invoice_number'] = isset($data['dispose_invoice_number']) ? $data['dispose_invoice_number'] : null;
        $this->container['dispose_shipment_tracking_number'] = isset($data['dispose_shipment_tracking_number']) ? $data['dispose_shipment_tracking_number'] : null;
        $this->container['dispose_license'] = isset($data['dispose_license']) ? $data['dispose_license'] : null;
        $this->container['dispose_license_name'] = isset($data['dispose_license_name']) ? $data['dispose_license_name'] : null;
        $this->container['dispose_license_expires'] = isset($data['dispose_license_expires']) ? $data['dispose_license_expires'] : null;
        $this->container['dispose_organization'] = isset($data['dispose_organization']) ? $data['dispose_organization'] : null;
        $this->container['dispose_first_name'] = isset($data['dispose_first_name']) ? $data['dispose_first_name'] : null;
        $this->container['dispose_last_name'] = isset($data['dispose_last_name']) ? $data['dispose_last_name'] : null;
        $this->container['dispose_address1'] = isset($data['dispose_address1']) ? $data['dispose_address1'] : null;
        $this->container['dispose_address2'] = isset($data['dispose_address2']) ? $data['dispose_address2'] : null;
        $this->container['dispose_city'] = isset($data['dispose_city']) ? $data['dispose_city'] : null;
        $this->container['dispose_state'] = isset($data['dispose_state']) ? $data['dispose_state'] : null;
        $this->container['dispose_postal'] = isset($data['dispose_postal']) ? $data['dispose_postal'] : null;
        $this->container['dispose_country'] = isset($data['dispose_country']) ? $data['dispose_country'] : null;
        $this->container['dispose_phone_number'] = isset($data['dispose_phone_number']) ? $data['dispose_phone_number'] : null;
        $this->container['dispose_fax'] = isset($data['dispose_fax']) ? $data['dispose_fax'] : null;
        $this->container['dispose_email_address'] = isset($data['dispose_email_address']) ? $data['dispose_email_address'] : null;
        $this->container['submission_date'] = isset($data['submission_date']) ? $data['submission_date'] : null;
        $this->container['theft_loss_discovered_date'] = isset($data['theft_loss_discovered_date']) ? $data['theft_loss_discovered_date'] : null;
        $this->container['theft_loss_type'] = isset($data['theft_loss_type']) ? $data['theft_loss_type'] : null;
        $this->container['theft_loss_atf_issued_incident_number'] = isset($data['theft_loss_atf_issued_incident_number']) ? $data['theft_loss_atf_issued_incident_number'] : null;
        $this->container['theft_loss_police_incident_number'] = isset($data['theft_loss_police_incident_number']) ? $data['theft_loss_police_incident_number'] : null;
        $this->container['destroyed_date'] = isset($data['destroyed_date']) ? $data['destroyed_date'] : null;
        $this->container['destroyed_description'] = isset($data['destroyed_description']) ? $data['destroyed_description'] : null;
        $this->container['destroyed_witness1'] = isset($data['destroyed_witness1']) ? $data['destroyed_witness1'] : null;
        $this->container['destroyed_witness2'] = isset($data['destroyed_witness2']) ? $data['destroyed_witness2'] : null;
        $this->container['multiple_sale_reports'] = isset($data['multiple_sale_reports']) ? $data['multiple_sale_reports'] : null;
        $this->container['lightspeed_system_id'] = isset($data['lightspeed_system_id']) ? $data['lightspeed_system_id'] : null;
        $this->container['lightspeed_serial_id'] = isset($data['lightspeed_serial_id']) ? $data['lightspeed_serial_id'] : null;
        $this->container['lightspeed_sale_id'] = isset($data['lightspeed_sale_id']) ? $data['lightspeed_sale_id'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['external_id'] = isset($data['external_id']) ? $data['external_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['disposition_id'] = isset($data['disposition_id']) ? $data['disposition_id'] : null;
        $this->container['disposition_external_id'] = isset($data['disposition_external_id']) ? $data['disposition_external_id'] : null;
        $this->container['create_utc'] = isset($data['create_utc']) ? $data['create_utc'] : null;
        $this->container['update_utc'] = isset($data['update_utc']) ? $data['update_utc'] : null;
        $this->container['quick_code_url'] = isset($data['quick_code_url']) ? $data['quick_code_url'] : null;
        $this->container['attachments'] = isset($data['attachments']) ? $data['attachments'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_number
     *
     * @return string
     */
    public function getItemNumber()
    {
        return $this->container['item_number'];
    }

    /**
     * Sets item_number
     *
     * @param string $item_number item_number
     *
     * @return $this
     */
    public function setItemNumber($item_number)
    {
        $this->container['item_number'] = $item_number;

        return $this;
    }

    /**
     * Gets do_not_dispose
     *
     * @return bool
     */
    public function getDoNotDispose()
    {
        return $this->container['do_not_dispose'];
    }

    /**
     * Sets do_not_dispose
     *
     * @param bool $do_not_dispose do_not_dispose
     *
     * @return $this
     */
    public function setDoNotDispose($do_not_dispose)
    {
        $this->container['do_not_dispose'] = $do_not_dispose;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string $manufacturer manufacturer
     *
     * @return $this
     */
    public function setManufacturer($manufacturer)
    {
        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets importer
     *
     * @return string
     */
    public function getImporter()
    {
        return $this->container['importer'];
    }

    /**
     * Sets importer
     *
     * @param string $importer importer
     *
     * @return $this
     */
    public function setImporter($importer)
    {
        $this->container['importer'] = $importer;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string $model model
     *
     * @return $this
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets serial
     *
     * @return string
     */
    public function getSerial()
    {
        return $this->container['serial'];
    }

    /**
     * Sets serial
     *
     * @param string $serial serial
     *
     * @return $this
     */
    public function setSerial($serial)
    {
        $this->container['serial'] = $serial;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets caliber
     *
     * @return string
     */
    public function getCaliber()
    {
        return $this->container['caliber'];
    }

    /**
     * Sets caliber
     *
     * @param string $caliber caliber
     *
     * @return $this
     */
    public function setCaliber($caliber)
    {
        $this->container['caliber'] = $caliber;

        return $this;
    }

    /**
     * Gets country_of_manufacture
     *
     * @return string
     */
    public function getCountryOfManufacture()
    {
        return $this->container['country_of_manufacture'];
    }

    /**
     * Sets country_of_manufacture
     *
     * @param string $country_of_manufacture country_of_manufacture
     *
     * @return $this
     */
    public function setCountryOfManufacture($country_of_manufacture)
    {
        $this->container['country_of_manufacture'] = $country_of_manufacture;

        return $this;
    }

    /**
     * Gets barrel_length
     *
     * @return double
     */
    public function getBarrelLength()
    {
        return $this->container['barrel_length'];
    }

    /**
     * Sets barrel_length
     *
     * @param double $barrel_length barrel_length
     *
     * @return $this
     */
    public function setBarrelLength($barrel_length)
    {
        $this->container['barrel_length'] = $barrel_length;

        return $this;
    }

    /**
     * Gets overall_length
     *
     * @return double
     */
    public function getOverallLength()
    {
        return $this->container['overall_length'];
    }

    /**
     * Sets overall_length
     *
     * @param double $overall_length overall_length
     *
     * @return $this
     */
    public function setOverallLength($overall_length)
    {
        $this->container['overall_length'] = $overall_length;

        return $this;
    }

    /**
     * Gets total_length
     *
     * @return double
     */
    public function getTotalLength()
    {
        return $this->container['total_length'];
    }

    /**
     * Sets total_length
     *
     * @param double $total_length This property has been there since the API was released and should have been called OverallLength. Because  callers might depend on it, we can't remove it; we can only deprecate it.
     *
     * @return $this
     */
    public function setTotalLength($total_length)
    {
        $this->container['total_length'] = $total_length;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string $condition condition
     *
     * @return $this
     */
    public function setCondition($condition)
    {
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets location_verified_utc
     *
     * @return \DateTime
     */
    public function getLocationVerifiedUtc()
    {
        return $this->container['location_verified_utc'];
    }

    /**
     * Sets location_verified_utc
     *
     * @param \DateTime $location_verified_utc location_verified_utc
     *
     * @return $this
     */
    public function setLocationVerifiedUtc($location_verified_utc)
    {
        $this->container['location_verified_utc'] = $location_verified_utc;

        return $this;
    }

    /**
     * Gets mpn
     *
     * @return string
     */
    public function getMpn()
    {
        return $this->container['mpn'];
    }

    /**
     * Sets mpn
     *
     * @param string $mpn mpn
     *
     * @return $this
     */
    public function setMpn($mpn)
    {
        $this->container['mpn'] = $mpn;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc upc
     *
     * @return $this
     */
    public function setUpc($upc)
    {
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string $sku sku
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return double
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param double $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets profit
     *
     * @return double
     */
    public function getProfit()
    {
        return $this->container['profit'];
    }

    /**
     * Sets profit
     *
     * @param double $profit profit
     *
     * @return $this
     */
    public function setProfit($profit)
    {
        $this->container['profit'] = $profit;

        return $this;
    }

    /**
     * Gets margin
     *
     * @return double
     */
    public function getMargin()
    {
        return $this->container['margin'];
    }

    /**
     * Sets margin
     *
     * @param double $margin margin
     *
     * @return $this
     */
    public function setMargin($margin)
    {
        $this->container['margin'] = $margin;

        return $this;
    }

    /**
     * Gets acquisition_type
     *
     * @return string
     */
    public function getAcquisitionType()
    {
        return $this->container['acquisition_type'];
    }

    /**
     * Sets acquisition_type
     *
     * @param string $acquisition_type acquisition_type
     *
     * @return $this
     */
    public function setAcquisitionType($acquisition_type)
    {
        $this->container['acquisition_type'] = $acquisition_type;

        return $this;
    }

    /**
     * Gets acquire_date
     *
     * @return \DateTime
     */
    public function getAcquireDate()
    {
        return $this->container['acquire_date'];
    }

    /**
     * Sets acquire_date
     *
     * @param \DateTime $acquire_date acquire_date
     *
     * @return $this
     */
    public function setAcquireDate($acquire_date)
    {
        $this->container['acquire_date'] = $acquire_date;

        return $this;
    }

    /**
     * Gets acquisition_user_email
     *
     * @return string
     */
    public function getAcquisitionUserEmail()
    {
        return $this->container['acquisition_user_email'];
    }

    /**
     * Sets acquisition_user_email
     *
     * @param string $acquisition_user_email acquisition_user_email
     *
     * @return $this
     */
    public function setAcquisitionUserEmail($acquisition_user_email)
    {
        $this->container['acquisition_user_email'] = $acquisition_user_email;

        return $this;
    }

    /**
     * Gets acquire_purchase_order_number
     *
     * @return string
     */
    public function getAcquirePurchaseOrderNumber()
    {
        return $this->container['acquire_purchase_order_number'];
    }

    /**
     * Sets acquire_purchase_order_number
     *
     * @param string $acquire_purchase_order_number acquire_purchase_order_number
     *
     * @return $this
     */
    public function setAcquirePurchaseOrderNumber($acquire_purchase_order_number)
    {
        $this->container['acquire_purchase_order_number'] = $acquire_purchase_order_number;

        return $this;
    }

    /**
     * Gets acquire_invoice_number
     *
     * @return string
     */
    public function getAcquireInvoiceNumber()
    {
        return $this->container['acquire_invoice_number'];
    }

    /**
     * Sets acquire_invoice_number
     *
     * @param string $acquire_invoice_number acquire_invoice_number
     *
     * @return $this
     */
    public function setAcquireInvoiceNumber($acquire_invoice_number)
    {
        $this->container['acquire_invoice_number'] = $acquire_invoice_number;

        return $this;
    }

    /**
     * Gets acquire_shipment_tracking_number
     *
     * @return string
     */
    public function getAcquireShipmentTrackingNumber()
    {
        return $this->container['acquire_shipment_tracking_number'];
    }

    /**
     * Sets acquire_shipment_tracking_number
     *
     * @param string $acquire_shipment_tracking_number acquire_shipment_tracking_number
     *
     * @return $this
     */
    public function setAcquireShipmentTrackingNumber($acquire_shipment_tracking_number)
    {
        $this->container['acquire_shipment_tracking_number'] = $acquire_shipment_tracking_number;

        return $this;
    }

    /**
     * Gets acquire_license
     *
     * @return string
     */
    public function getAcquireLicense()
    {
        return $this->container['acquire_license'];
    }

    /**
     * Sets acquire_license
     *
     * @param string $acquire_license acquire_license
     *
     * @return $this
     */
    public function setAcquireLicense($acquire_license)
    {
        $this->container['acquire_license'] = $acquire_license;

        return $this;
    }

    /**
     * Gets acquire_license_name
     *
     * @return string
     */
    public function getAcquireLicenseName()
    {
        return $this->container['acquire_license_name'];
    }

    /**
     * Sets acquire_license_name
     *
     * @param string $acquire_license_name acquire_license_name
     *
     * @return $this
     */
    public function setAcquireLicenseName($acquire_license_name)
    {
        $this->container['acquire_license_name'] = $acquire_license_name;

        return $this;
    }

    /**
     * Gets acquire_license_expires
     *
     * @return \DateTime
     */
    public function getAcquireLicenseExpires()
    {
        return $this->container['acquire_license_expires'];
    }

    /**
     * Sets acquire_license_expires
     *
     * @param \DateTime $acquire_license_expires acquire_license_expires
     *
     * @return $this
     */
    public function setAcquireLicenseExpires($acquire_license_expires)
    {
        $this->container['acquire_license_expires'] = $acquire_license_expires;

        return $this;
    }

    /**
     * Gets acquire_organization
     *
     * @return string
     */
    public function getAcquireOrganization()
    {
        return $this->container['acquire_organization'];
    }

    /**
     * Sets acquire_organization
     *
     * @param string $acquire_organization acquire_organization
     *
     * @return $this
     */
    public function setAcquireOrganization($acquire_organization)
    {
        $this->container['acquire_organization'] = $acquire_organization;

        return $this;
    }

    /**
     * Gets acquire_first_name
     *
     * @return string
     */
    public function getAcquireFirstName()
    {
        return $this->container['acquire_first_name'];
    }

    /**
     * Sets acquire_first_name
     *
     * @param string $acquire_first_name acquire_first_name
     *
     * @return $this
     */
    public function setAcquireFirstName($acquire_first_name)
    {
        $this->container['acquire_first_name'] = $acquire_first_name;

        return $this;
    }

    /**
     * Gets acquire_last_name
     *
     * @return string
     */
    public function getAcquireLastName()
    {
        return $this->container['acquire_last_name'];
    }

    /**
     * Sets acquire_last_name
     *
     * @param string $acquire_last_name acquire_last_name
     *
     * @return $this
     */
    public function setAcquireLastName($acquire_last_name)
    {
        $this->container['acquire_last_name'] = $acquire_last_name;

        return $this;
    }

    /**
     * Gets acquire_address1
     *
     * @return string
     */
    public function getAcquireAddress1()
    {
        return $this->container['acquire_address1'];
    }

    /**
     * Sets acquire_address1
     *
     * @param string $acquire_address1 acquire_address1
     *
     * @return $this
     */
    public function setAcquireAddress1($acquire_address1)
    {
        $this->container['acquire_address1'] = $acquire_address1;

        return $this;
    }

    /**
     * Gets acquire_address2
     *
     * @return string
     */
    public function getAcquireAddress2()
    {
        return $this->container['acquire_address2'];
    }

    /**
     * Sets acquire_address2
     *
     * @param string $acquire_address2 acquire_address2
     *
     * @return $this
     */
    public function setAcquireAddress2($acquire_address2)
    {
        $this->container['acquire_address2'] = $acquire_address2;

        return $this;
    }

    /**
     * Gets acquire_city
     *
     * @return string
     */
    public function getAcquireCity()
    {
        return $this->container['acquire_city'];
    }

    /**
     * Sets acquire_city
     *
     * @param string $acquire_city acquire_city
     *
     * @return $this
     */
    public function setAcquireCity($acquire_city)
    {
        $this->container['acquire_city'] = $acquire_city;

        return $this;
    }

    /**
     * Gets acquire_state
     *
     * @return string
     */
    public function getAcquireState()
    {
        return $this->container['acquire_state'];
    }

    /**
     * Sets acquire_state
     *
     * @param string $acquire_state acquire_state
     *
     * @return $this
     */
    public function setAcquireState($acquire_state)
    {
        $this->container['acquire_state'] = $acquire_state;

        return $this;
    }

    /**
     * Gets acquire_postal
     *
     * @return string
     */
    public function getAcquirePostal()
    {
        return $this->container['acquire_postal'];
    }

    /**
     * Sets acquire_postal
     *
     * @param string $acquire_postal acquire_postal
     *
     * @return $this
     */
    public function setAcquirePostal($acquire_postal)
    {
        $this->container['acquire_postal'] = $acquire_postal;

        return $this;
    }

    /**
     * Gets acquire_country
     *
     * @return string
     */
    public function getAcquireCountry()
    {
        return $this->container['acquire_country'];
    }

    /**
     * Sets acquire_country
     *
     * @param string $acquire_country acquire_country
     *
     * @return $this
     */
    public function setAcquireCountry($acquire_country)
    {
        $this->container['acquire_country'] = $acquire_country;

        return $this;
    }

    /**
     * Gets acquire_phone_number
     *
     * @return string
     */
    public function getAcquirePhoneNumber()
    {
        return $this->container['acquire_phone_number'];
    }

    /**
     * Sets acquire_phone_number
     *
     * @param string $acquire_phone_number acquire_phone_number
     *
     * @return $this
     */
    public function setAcquirePhoneNumber($acquire_phone_number)
    {
        $this->container['acquire_phone_number'] = $acquire_phone_number;

        return $this;
    }

    /**
     * Gets acquire_fax
     *
     * @return string
     */
    public function getAcquireFax()
    {
        return $this->container['acquire_fax'];
    }

    /**
     * Sets acquire_fax
     *
     * @param string $acquire_fax acquire_fax
     *
     * @return $this
     */
    public function setAcquireFax($acquire_fax)
    {
        $this->container['acquire_fax'] = $acquire_fax;

        return $this;
    }

    /**
     * Gets acquire_email_address
     *
     * @return string
     */
    public function getAcquireEmailAddress()
    {
        return $this->container['acquire_email_address'];
    }

    /**
     * Sets acquire_email_address
     *
     * @param string $acquire_email_address acquire_email_address
     *
     * @return $this
     */
    public function setAcquireEmailAddress($acquire_email_address)
    {
        $this->container['acquire_email_address'] = $acquire_email_address;

        return $this;
    }

    /**
     * Gets disposition_type
     *
     * @return string
     */
    public function getDispositionType()
    {
        return $this->container['disposition_type'];
    }

    /**
     * Sets disposition_type
     *
     * @param string $disposition_type disposition_type
     *
     * @return $this
     */
    public function setDispositionType($disposition_type)
    {
        $this->container['disposition_type'] = $disposition_type;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool $deleted deleted
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets dispose_date
     *
     * @return \DateTime
     */
    public function getDisposeDate()
    {
        return $this->container['dispose_date'];
    }

    /**
     * Sets dispose_date
     *
     * @param \DateTime $dispose_date dispose_date
     *
     * @return $this
     */
    public function setDisposeDate($dispose_date)
    {
        $this->container['dispose_date'] = $dispose_date;

        return $this;
    }

    /**
     * Gets ttsn
     *
     * @return string
     */
    public function getTtsn()
    {
        return $this->container['ttsn'];
    }

    /**
     * Sets ttsn
     *
     * @param string $ttsn ttsn
     *
     * @return $this
     */
    public function setTtsn($ttsn)
    {
        $this->container['ttsn'] = $ttsn;

        return $this;
    }

    /**
     * Gets otsn
     *
     * @return string
     */
    public function getOtsn()
    {
        return $this->container['otsn'];
    }

    /**
     * Sets otsn
     *
     * @param string $otsn otsn
     *
     * @return $this
     */
    public function setOtsn($otsn)
    {
        $this->container['otsn'] = $otsn;

        return $this;
    }

    /**
     * Gets disposition_user_email
     *
     * @return string
     */
    public function getDispositionUserEmail()
    {
        return $this->container['disposition_user_email'];
    }

    /**
     * Sets disposition_user_email
     *
     * @param string $disposition_user_email disposition_user_email
     *
     * @return $this
     */
    public function setDispositionUserEmail($disposition_user_email)
    {
        $this->container['disposition_user_email'] = $disposition_user_email;

        return $this;
    }

    /**
     * Gets dispose_purchase_order_number
     *
     * @return string
     */
    public function getDisposePurchaseOrderNumber()
    {
        return $this->container['dispose_purchase_order_number'];
    }

    /**
     * Sets dispose_purchase_order_number
     *
     * @param string $dispose_purchase_order_number dispose_purchase_order_number
     *
     * @return $this
     */
    public function setDisposePurchaseOrderNumber($dispose_purchase_order_number)
    {
        $this->container['dispose_purchase_order_number'] = $dispose_purchase_order_number;

        return $this;
    }

    /**
     * Gets dispose_invoice_number
     *
     * @return string
     */
    public function getDisposeInvoiceNumber()
    {
        return $this->container['dispose_invoice_number'];
    }

    /**
     * Sets dispose_invoice_number
     *
     * @param string $dispose_invoice_number dispose_invoice_number
     *
     * @return $this
     */
    public function setDisposeInvoiceNumber($dispose_invoice_number)
    {
        $this->container['dispose_invoice_number'] = $dispose_invoice_number;

        return $this;
    }

    /**
     * Gets dispose_shipment_tracking_number
     *
     * @return string
     */
    public function getDisposeShipmentTrackingNumber()
    {
        return $this->container['dispose_shipment_tracking_number'];
    }

    /**
     * Sets dispose_shipment_tracking_number
     *
     * @param string $dispose_shipment_tracking_number dispose_shipment_tracking_number
     *
     * @return $this
     */
    public function setDisposeShipmentTrackingNumber($dispose_shipment_tracking_number)
    {
        $this->container['dispose_shipment_tracking_number'] = $dispose_shipment_tracking_number;

        return $this;
    }

    /**
     * Gets dispose_license
     *
     * @return string
     */
    public function getDisposeLicense()
    {
        return $this->container['dispose_license'];
    }

    /**
     * Sets dispose_license
     *
     * @param string $dispose_license dispose_license
     *
     * @return $this
     */
    public function setDisposeLicense($dispose_license)
    {
        $this->container['dispose_license'] = $dispose_license;

        return $this;
    }

    /**
     * Gets dispose_license_name
     *
     * @return string
     */
    public function getDisposeLicenseName()
    {
        return $this->container['dispose_license_name'];
    }

    /**
     * Sets dispose_license_name
     *
     * @param string $dispose_license_name dispose_license_name
     *
     * @return $this
     */
    public function setDisposeLicenseName($dispose_license_name)
    {
        $this->container['dispose_license_name'] = $dispose_license_name;

        return $this;
    }

    /**
     * Gets dispose_license_expires
     *
     * @return \DateTime
     */
    public function getDisposeLicenseExpires()
    {
        return $this->container['dispose_license_expires'];
    }

    /**
     * Sets dispose_license_expires
     *
     * @param \DateTime $dispose_license_expires dispose_license_expires
     *
     * @return $this
     */
    public function setDisposeLicenseExpires($dispose_license_expires)
    {
        $this->container['dispose_license_expires'] = $dispose_license_expires;

        return $this;
    }

    /**
     * Gets dispose_organization
     *
     * @return string
     */
    public function getDisposeOrganization()
    {
        return $this->container['dispose_organization'];
    }

    /**
     * Sets dispose_organization
     *
     * @param string $dispose_organization dispose_organization
     *
     * @return $this
     */
    public function setDisposeOrganization($dispose_organization)
    {
        $this->container['dispose_organization'] = $dispose_organization;

        return $this;
    }

    /**
     * Gets dispose_first_name
     *
     * @return string
     */
    public function getDisposeFirstName()
    {
        return $this->container['dispose_first_name'];
    }

    /**
     * Sets dispose_first_name
     *
     * @param string $dispose_first_name dispose_first_name
     *
     * @return $this
     */
    public function setDisposeFirstName($dispose_first_name)
    {
        $this->container['dispose_first_name'] = $dispose_first_name;

        return $this;
    }

    /**
     * Gets dispose_last_name
     *
     * @return string
     */
    public function getDisposeLastName()
    {
        return $this->container['dispose_last_name'];
    }

    /**
     * Sets dispose_last_name
     *
     * @param string $dispose_last_name dispose_last_name
     *
     * @return $this
     */
    public function setDisposeLastName($dispose_last_name)
    {
        $this->container['dispose_last_name'] = $dispose_last_name;

        return $this;
    }

    /**
     * Gets dispose_address1
     *
     * @return string
     */
    public function getDisposeAddress1()
    {
        return $this->container['dispose_address1'];
    }

    /**
     * Sets dispose_address1
     *
     * @param string $dispose_address1 dispose_address1
     *
     * @return $this
     */
    public function setDisposeAddress1($dispose_address1)
    {
        $this->container['dispose_address1'] = $dispose_address1;

        return $this;
    }

    /**
     * Gets dispose_address2
     *
     * @return string
     */
    public function getDisposeAddress2()
    {
        return $this->container['dispose_address2'];
    }

    /**
     * Sets dispose_address2
     *
     * @param string $dispose_address2 dispose_address2
     *
     * @return $this
     */
    public function setDisposeAddress2($dispose_address2)
    {
        $this->container['dispose_address2'] = $dispose_address2;

        return $this;
    }

    /**
     * Gets dispose_city
     *
     * @return string
     */
    public function getDisposeCity()
    {
        return $this->container['dispose_city'];
    }

    /**
     * Sets dispose_city
     *
     * @param string $dispose_city dispose_city
     *
     * @return $this
     */
    public function setDisposeCity($dispose_city)
    {
        $this->container['dispose_city'] = $dispose_city;

        return $this;
    }

    /**
     * Gets dispose_state
     *
     * @return string
     */
    public function getDisposeState()
    {
        return $this->container['dispose_state'];
    }

    /**
     * Sets dispose_state
     *
     * @param string $dispose_state dispose_state
     *
     * @return $this
     */
    public function setDisposeState($dispose_state)
    {
        $this->container['dispose_state'] = $dispose_state;

        return $this;
    }

    /**
     * Gets dispose_postal
     *
     * @return string
     */
    public function getDisposePostal()
    {
        return $this->container['dispose_postal'];
    }

    /**
     * Sets dispose_postal
     *
     * @param string $dispose_postal dispose_postal
     *
     * @return $this
     */
    public function setDisposePostal($dispose_postal)
    {
        $this->container['dispose_postal'] = $dispose_postal;

        return $this;
    }

    /**
     * Gets dispose_country
     *
     * @return string
     */
    public function getDisposeCountry()
    {
        return $this->container['dispose_country'];
    }

    /**
     * Sets dispose_country
     *
     * @param string $dispose_country dispose_country
     *
     * @return $this
     */
    public function setDisposeCountry($dispose_country)
    {
        $this->container['dispose_country'] = $dispose_country;

        return $this;
    }

    /**
     * Gets dispose_phone_number
     *
     * @return string
     */
    public function getDisposePhoneNumber()
    {
        return $this->container['dispose_phone_number'];
    }

    /**
     * Sets dispose_phone_number
     *
     * @param string $dispose_phone_number dispose_phone_number
     *
     * @return $this
     */
    public function setDisposePhoneNumber($dispose_phone_number)
    {
        $this->container['dispose_phone_number'] = $dispose_phone_number;

        return $this;
    }

    /**
     * Gets dispose_fax
     *
     * @return string
     */
    public function getDisposeFax()
    {
        return $this->container['dispose_fax'];
    }

    /**
     * Sets dispose_fax
     *
     * @param string $dispose_fax dispose_fax
     *
     * @return $this
     */
    public function setDisposeFax($dispose_fax)
    {
        $this->container['dispose_fax'] = $dispose_fax;

        return $this;
    }

    /**
     * Gets dispose_email_address
     *
     * @return string
     */
    public function getDisposeEmailAddress()
    {
        return $this->container['dispose_email_address'];
    }

    /**
     * Sets dispose_email_address
     *
     * @param string $dispose_email_address dispose_email_address
     *
     * @return $this
     */
    public function setDisposeEmailAddress($dispose_email_address)
    {
        $this->container['dispose_email_address'] = $dispose_email_address;

        return $this;
    }

    /**
     * Gets submission_date
     *
     * @return \DateTime
     */
    public function getSubmissionDate()
    {
        return $this->container['submission_date'];
    }

    /**
     * Sets submission_date
     *
     * @param \DateTime $submission_date submission_date
     *
     * @return $this
     */
    public function setSubmissionDate($submission_date)
    {
        $this->container['submission_date'] = $submission_date;

        return $this;
    }

    /**
     * Gets theft_loss_discovered_date
     *
     * @return \DateTime
     */
    public function getTheftLossDiscoveredDate()
    {
        return $this->container['theft_loss_discovered_date'];
    }

    /**
     * Sets theft_loss_discovered_date
     *
     * @param \DateTime $theft_loss_discovered_date theft_loss_discovered_date
     *
     * @return $this
     */
    public function setTheftLossDiscoveredDate($theft_loss_discovered_date)
    {
        $this->container['theft_loss_discovered_date'] = $theft_loss_discovered_date;

        return $this;
    }

    /**
     * Gets theft_loss_type
     *
     * @return string
     */
    public function getTheftLossType()
    {
        return $this->container['theft_loss_type'];
    }

    /**
     * Sets theft_loss_type
     *
     * @param string $theft_loss_type theft_loss_type
     *
     * @return $this
     */
    public function setTheftLossType($theft_loss_type)
    {
        $this->container['theft_loss_type'] = $theft_loss_type;

        return $this;
    }

    /**
     * Gets theft_loss_atf_issued_incident_number
     *
     * @return string
     */
    public function getTheftLossAtfIssuedIncidentNumber()
    {
        return $this->container['theft_loss_atf_issued_incident_number'];
    }

    /**
     * Sets theft_loss_atf_issued_incident_number
     *
     * @param string $theft_loss_atf_issued_incident_number theft_loss_atf_issued_incident_number
     *
     * @return $this
     */
    public function setTheftLossAtfIssuedIncidentNumber($theft_loss_atf_issued_incident_number)
    {
        $this->container['theft_loss_atf_issued_incident_number'] = $theft_loss_atf_issued_incident_number;

        return $this;
    }

    /**
     * Gets theft_loss_police_incident_number
     *
     * @return string
     */
    public function getTheftLossPoliceIncidentNumber()
    {
        return $this->container['theft_loss_police_incident_number'];
    }

    /**
     * Sets theft_loss_police_incident_number
     *
     * @param string $theft_loss_police_incident_number theft_loss_police_incident_number
     *
     * @return $this
     */
    public function setTheftLossPoliceIncidentNumber($theft_loss_police_incident_number)
    {
        $this->container['theft_loss_police_incident_number'] = $theft_loss_police_incident_number;

        return $this;
    }

    /**
     * Gets destroyed_date
     *
     * @return \DateTime
     */
    public function getDestroyedDate()
    {
        return $this->container['destroyed_date'];
    }

    /**
     * Sets destroyed_date
     *
     * @param \DateTime $destroyed_date destroyed_date
     *
     * @return $this
     */
    public function setDestroyedDate($destroyed_date)
    {
        $this->container['destroyed_date'] = $destroyed_date;

        return $this;
    }

    /**
     * Gets destroyed_description
     *
     * @return string
     */
    public function getDestroyedDescription()
    {
        return $this->container['destroyed_description'];
    }

    /**
     * Sets destroyed_description
     *
     * @param string $destroyed_description destroyed_description
     *
     * @return $this
     */
    public function setDestroyedDescription($destroyed_description)
    {
        $this->container['destroyed_description'] = $destroyed_description;

        return $this;
    }

    /**
     * Gets destroyed_witness1
     *
     * @return string
     */
    public function getDestroyedWitness1()
    {
        return $this->container['destroyed_witness1'];
    }

    /**
     * Sets destroyed_witness1
     *
     * @param string $destroyed_witness1 destroyed_witness1
     *
     * @return $this
     */
    public function setDestroyedWitness1($destroyed_witness1)
    {
        $this->container['destroyed_witness1'] = $destroyed_witness1;

        return $this;
    }

    /**
     * Gets destroyed_witness2
     *
     * @return string
     */
    public function getDestroyedWitness2()
    {
        return $this->container['destroyed_witness2'];
    }

    /**
     * Sets destroyed_witness2
     *
     * @param string $destroyed_witness2 destroyed_witness2
     *
     * @return $this
     */
    public function setDestroyedWitness2($destroyed_witness2)
    {
        $this->container['destroyed_witness2'] = $destroyed_witness2;

        return $this;
    }

    /**
     * Gets multiple_sale_reports
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsGetItemCommandMultipleSaleReportModel[]
     */
    public function getMultipleSaleReports()
    {
        return $this->container['multiple_sale_reports'];
    }

    /**
     * Sets multiple_sale_reports
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsGetItemCommandMultipleSaleReportModel[] $multiple_sale_reports multiple_sale_reports
     *
     * @return $this
     */
    public function setMultipleSaleReports($multiple_sale_reports)
    {
        $this->container['multiple_sale_reports'] = $multiple_sale_reports;

        return $this;
    }

    /**
     * Gets lightspeed_system_id
     *
     * @return int
     */
    public function getLightspeedSystemId()
    {
        return $this->container['lightspeed_system_id'];
    }

    /**
     * Sets lightspeed_system_id
     *
     * @param int $lightspeed_system_id lightspeed_system_id
     *
     * @return $this
     */
    public function setLightspeedSystemId($lightspeed_system_id)
    {
        $this->container['lightspeed_system_id'] = $lightspeed_system_id;

        return $this;
    }

    /**
     * Gets lightspeed_serial_id
     *
     * @return int
     */
    public function getLightspeedSerialId()
    {
        return $this->container['lightspeed_serial_id'];
    }

    /**
     * Sets lightspeed_serial_id
     *
     * @param int $lightspeed_serial_id lightspeed_serial_id
     *
     * @return $this
     */
    public function setLightspeedSerialId($lightspeed_serial_id)
    {
        $this->container['lightspeed_serial_id'] = $lightspeed_serial_id;

        return $this;
    }

    /**
     * Gets lightspeed_sale_id
     *
     * @return int
     */
    public function getLightspeedSaleId()
    {
        return $this->container['lightspeed_sale_id'];
    }

    /**
     * Sets lightspeed_sale_id
     *
     * @param int $lightspeed_sale_id lightspeed_sale_id
     *
     * @return $this
     */
    public function setLightspeedSaleId($lightspeed_sale_id)
    {
        $this->container['lightspeed_sale_id'] = $lightspeed_sale_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string $external_id external_id
     *
     * @return $this
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets disposition_id
     *
     * @return string
     */
    public function getDispositionId()
    {
        return $this->container['disposition_id'];
    }

    /**
     * Sets disposition_id
     *
     * @param string $disposition_id disposition_id
     *
     * @return $this
     */
    public function setDispositionId($disposition_id)
    {
        $this->container['disposition_id'] = $disposition_id;

        return $this;
    }

    /**
     * Gets disposition_external_id
     *
     * @return string
     */
    public function getDispositionExternalId()
    {
        return $this->container['disposition_external_id'];
    }

    /**
     * Sets disposition_external_id
     *
     * @param string $disposition_external_id disposition_external_id
     *
     * @return $this
     */
    public function setDispositionExternalId($disposition_external_id)
    {
        $this->container['disposition_external_id'] = $disposition_external_id;

        return $this;
    }

    /**
     * Gets create_utc
     *
     * @return \DateTime
     */
    public function getCreateUtc()
    {
        return $this->container['create_utc'];
    }

    /**
     * Sets create_utc
     *
     * @param \DateTime $create_utc create_utc
     *
     * @return $this
     */
    public function setCreateUtc($create_utc)
    {
        $this->container['create_utc'] = $create_utc;

        return $this;
    }

    /**
     * Gets update_utc
     *
     * @return \DateTime
     */
    public function getUpdateUtc()
    {
        return $this->container['update_utc'];
    }

    /**
     * Sets update_utc
     *
     * @param \DateTime $update_utc update_utc
     *
     * @return $this
     */
    public function setUpdateUtc($update_utc)
    {
        $this->container['update_utc'] = $update_utc;

        return $this;
    }

    /**
     * Gets quick_code_url
     *
     * @return string
     */
    public function getQuickCodeUrl()
    {
        return $this->container['quick_code_url'];
    }

    /**
     * Sets quick_code_url
     *
     * @param string $quick_code_url quick_code_url
     *
     * @return $this
     */
    public function setQuickCodeUrl($quick_code_url)
    {
        $this->container['quick_code_url'] = $quick_code_url;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[]
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[] $attachments attachments
     *
     * @return $this
     */
    public function setAttachments($attachments)
    {
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[]
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[] $notes notes
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
