<?php
/**
 * FastBoundWebModelsApiV1AccountGetAccountCommandOwnerContactModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FastBoundWebModelsApiV1AccountGetAccountCommandOwnerContactModel Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1AccountGetAccountCommandOwnerContactModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FastBound.Web.Models.Api.V1.Account.GetAccount+Command+OwnerContactModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'license_name' => 'string',
        'trade_name' => 'string',
        'premise_address1' => 'string',
        'premise_address2' => 'string',
        'premise_city' => 'string',
        'premise_state' => 'string',
        'premise_zip_code' => 'string',
        'premise_country' => 'string',
        'ffl_number' => 'string',
        'ffl_expires' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'license_name' => null,
        'trade_name' => null,
        'premise_address1' => null,
        'premise_address2' => null,
        'premise_city' => null,
        'premise_state' => null,
        'premise_zip_code' => null,
        'premise_country' => null,
        'ffl_number' => null,
        'ffl_expires' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'license_name' => 'licenseName',
        'trade_name' => 'tradeName',
        'premise_address1' => 'premiseAddress1',
        'premise_address2' => 'premiseAddress2',
        'premise_city' => 'premiseCity',
        'premise_state' => 'premiseState',
        'premise_zip_code' => 'premiseZipCode',
        'premise_country' => 'premiseCountry',
        'ffl_number' => 'fflNumber',
        'ffl_expires' => 'fflExpires'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'license_name' => 'setLicenseName',
        'trade_name' => 'setTradeName',
        'premise_address1' => 'setPremiseAddress1',
        'premise_address2' => 'setPremiseAddress2',
        'premise_city' => 'setPremiseCity',
        'premise_state' => 'setPremiseState',
        'premise_zip_code' => 'setPremiseZipCode',
        'premise_country' => 'setPremiseCountry',
        'ffl_number' => 'setFflNumber',
        'ffl_expires' => 'setFflExpires'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'license_name' => 'getLicenseName',
        'trade_name' => 'getTradeName',
        'premise_address1' => 'getPremiseAddress1',
        'premise_address2' => 'getPremiseAddress2',
        'premise_city' => 'getPremiseCity',
        'premise_state' => 'getPremiseState',
        'premise_zip_code' => 'getPremiseZipCode',
        'premise_country' => 'getPremiseCountry',
        'ffl_number' => 'getFflNumber',
        'ffl_expires' => 'getFflExpires'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['license_name'] = isset($data['license_name']) ? $data['license_name'] : null;
        $this->container['trade_name'] = isset($data['trade_name']) ? $data['trade_name'] : null;
        $this->container['premise_address1'] = isset($data['premise_address1']) ? $data['premise_address1'] : null;
        $this->container['premise_address2'] = isset($data['premise_address2']) ? $data['premise_address2'] : null;
        $this->container['premise_city'] = isset($data['premise_city']) ? $data['premise_city'] : null;
        $this->container['premise_state'] = isset($data['premise_state']) ? $data['premise_state'] : null;
        $this->container['premise_zip_code'] = isset($data['premise_zip_code']) ? $data['premise_zip_code'] : null;
        $this->container['premise_country'] = isset($data['premise_country']) ? $data['premise_country'] : null;
        $this->container['ffl_number'] = isset($data['ffl_number']) ? $data['ffl_number'] : null;
        $this->container['ffl_expires'] = isset($data['ffl_expires']) ? $data['ffl_expires'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets license_name
     *
     * @return string
     */
    public function getLicenseName()
    {
        return $this->container['license_name'];
    }

    /**
     * Sets license_name
     *
     * @param string $license_name license_name
     *
     * @return $this
     */
    public function setLicenseName($license_name)
    {
        $this->container['license_name'] = $license_name;

        return $this;
    }

    /**
     * Gets trade_name
     *
     * @return string
     */
    public function getTradeName()
    {
        return $this->container['trade_name'];
    }

    /**
     * Sets trade_name
     *
     * @param string $trade_name trade_name
     *
     * @return $this
     */
    public function setTradeName($trade_name)
    {
        $this->container['trade_name'] = $trade_name;

        return $this;
    }

    /**
     * Gets premise_address1
     *
     * @return string
     */
    public function getPremiseAddress1()
    {
        return $this->container['premise_address1'];
    }

    /**
     * Sets premise_address1
     *
     * @param string $premise_address1 premise_address1
     *
     * @return $this
     */
    public function setPremiseAddress1($premise_address1)
    {
        $this->container['premise_address1'] = $premise_address1;

        return $this;
    }

    /**
     * Gets premise_address2
     *
     * @return string
     */
    public function getPremiseAddress2()
    {
        return $this->container['premise_address2'];
    }

    /**
     * Sets premise_address2
     *
     * @param string $premise_address2 premise_address2
     *
     * @return $this
     */
    public function setPremiseAddress2($premise_address2)
    {
        $this->container['premise_address2'] = $premise_address2;

        return $this;
    }

    /**
     * Gets premise_city
     *
     * @return string
     */
    public function getPremiseCity()
    {
        return $this->container['premise_city'];
    }

    /**
     * Sets premise_city
     *
     * @param string $premise_city premise_city
     *
     * @return $this
     */
    public function setPremiseCity($premise_city)
    {
        $this->container['premise_city'] = $premise_city;

        return $this;
    }

    /**
     * Gets premise_state
     *
     * @return string
     */
    public function getPremiseState()
    {
        return $this->container['premise_state'];
    }

    /**
     * Sets premise_state
     *
     * @param string $premise_state premise_state
     *
     * @return $this
     */
    public function setPremiseState($premise_state)
    {
        $this->container['premise_state'] = $premise_state;

        return $this;
    }

    /**
     * Gets premise_zip_code
     *
     * @return string
     */
    public function getPremiseZipCode()
    {
        return $this->container['premise_zip_code'];
    }

    /**
     * Sets premise_zip_code
     *
     * @param string $premise_zip_code premise_zip_code
     *
     * @return $this
     */
    public function setPremiseZipCode($premise_zip_code)
    {
        $this->container['premise_zip_code'] = $premise_zip_code;

        return $this;
    }

    /**
     * Gets premise_country
     *
     * @return string
     */
    public function getPremiseCountry()
    {
        return $this->container['premise_country'];
    }

    /**
     * Sets premise_country
     *
     * @param string $premise_country premise_country
     *
     * @return $this
     */
    public function setPremiseCountry($premise_country)
    {
        $this->container['premise_country'] = $premise_country;

        return $this;
    }

    /**
     * Gets ffl_number
     *
     * @return string
     */
    public function getFflNumber()
    {
        return $this->container['ffl_number'];
    }

    /**
     * Sets ffl_number
     *
     * @param string $ffl_number ffl_number
     *
     * @return $this
     */
    public function setFflNumber($ffl_number)
    {
        $this->container['ffl_number'] = $ffl_number;

        return $this;
    }

    /**
     * Gets ffl_expires
     *
     * @return \DateTime
     */
    public function getFflExpires()
    {
        return $this->container['ffl_expires'];
    }

    /**
     * Sets ffl_expires
     *
     * @param \DateTime $ffl_expires ffl_expires
     *
     * @return $this
     */
    public function setFflExpires($ffl_expires)
    {
        $this->container['ffl_expires'] = $ffl_expires;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
