<?php
/**
 * FastBoundWebModelsApiV1ItemsGetAllCommandItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FastBoundWebModelsApiV1ItemsGetAllCommandItem Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ItemsGetAllCommandItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FastBound.Web.Models.Api.V1.Items.GetAll+Command+Item';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'item_number' => 'string',
        'serial' => 'string',
        'manufacturer' => 'string',
        'country_of_manufacture' => 'string',
        'importer' => 'string',
        'model' => 'string',
        'type' => 'string',
        'caliber' => 'string',
        'location' => 'string',
        'location_verified_utc' => '\DateTime',
        'condition' => 'string',
        'mpn' => 'string',
        'upc' => 'string',
        'sku' => 'string',
        'barrel_length' => 'double',
        'overall_length' => 'double',
        'acquisition_type' => 'string',
        'acquire_date' => '\DateTime',
        'acquisition_contact_id' => 'string',
        'acquire_purchase_order_number' => 'string',
        'acquire_invoice_number' => 'string',
        'acquire_shipment_tracking_number' => 'string',
        'disposition_type' => 'string',
        'dispose_date' => '\DateTime',
        'disposition_contact_id' => 'string',
        'dispose_purchase_order_number' => 'string',
        'dispose_invoice_number' => 'string',
        'dispose_shipment_tracking_number' => 'string',
        'deleted' => 'bool',
        'disposed' => 'bool',
        'is_theft_loss' => 'bool',
        'is_destroyed' => 'bool',
        'do_not_dispose' => 'bool',
        'price' => 'double',
        'cost' => 'double',
        'id' => 'string',
        'external_id' => 'string',
        'status' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel',
        'disposition_id' => 'string',
        'disposition_external_id' => 'string',
        'create_utc' => '\DateTime',
        'update_utc' => '\DateTime',
        'quick_code_url' => 'string',
        'attachments' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[]',
        'notes' => '\Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'item_number' => null,
        'serial' => null,
        'manufacturer' => null,
        'country_of_manufacture' => null,
        'importer' => null,
        'model' => null,
        'type' => null,
        'caliber' => null,
        'location' => null,
        'location_verified_utc' => 'date-time',
        'condition' => null,
        'mpn' => null,
        'upc' => null,
        'sku' => null,
        'barrel_length' => 'double',
        'overall_length' => 'double',
        'acquisition_type' => null,
        'acquire_date' => 'date-time',
        'acquisition_contact_id' => 'uuid',
        'acquire_purchase_order_number' => null,
        'acquire_invoice_number' => null,
        'acquire_shipment_tracking_number' => null,
        'disposition_type' => null,
        'dispose_date' => 'date-time',
        'disposition_contact_id' => 'uuid',
        'dispose_purchase_order_number' => null,
        'dispose_invoice_number' => null,
        'dispose_shipment_tracking_number' => null,
        'deleted' => null,
        'disposed' => null,
        'is_theft_loss' => null,
        'is_destroyed' => null,
        'do_not_dispose' => null,
        'price' => 'double',
        'cost' => 'double',
        'id' => 'uuid',
        'external_id' => null,
        'status' => null,
        'disposition_id' => 'uuid',
        'disposition_external_id' => null,
        'create_utc' => 'date-time',
        'update_utc' => 'date-time',
        'quick_code_url' => null,
        'attachments' => null,
        'notes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_number' => 'itemNumber',
        'serial' => 'serial',
        'manufacturer' => 'manufacturer',
        'country_of_manufacture' => 'countryOfManufacture',
        'importer' => 'importer',
        'model' => 'model',
        'type' => 'type',
        'caliber' => 'caliber',
        'location' => 'location',
        'location_verified_utc' => 'locationVerifiedUtc',
        'condition' => 'condition',
        'mpn' => 'mpn',
        'upc' => 'upc',
        'sku' => 'sku',
        'barrel_length' => 'barrelLength',
        'overall_length' => 'overallLength',
        'acquisition_type' => 'acquisitionType',
        'acquire_date' => 'acquire_Date',
        'acquisition_contact_id' => 'acquisitionContactId',
        'acquire_purchase_order_number' => 'acquire_PurchaseOrderNumber',
        'acquire_invoice_number' => 'acquire_InvoiceNumber',
        'acquire_shipment_tracking_number' => 'acquire_ShipmentTrackingNumber',
        'disposition_type' => 'dispositionType',
        'dispose_date' => 'dispose_Date',
        'disposition_contact_id' => 'dispositionContactId',
        'dispose_purchase_order_number' => 'dispose_PurchaseOrderNumber',
        'dispose_invoice_number' => 'dispose_InvoiceNumber',
        'dispose_shipment_tracking_number' => 'dispose_ShipmentTrackingNumber',
        'deleted' => 'deleted',
        'disposed' => 'disposed',
        'is_theft_loss' => 'isTheftLoss',
        'is_destroyed' => 'isDestroyed',
        'do_not_dispose' => 'doNotDispose',
        'price' => 'price',
        'cost' => 'cost',
        'id' => 'id',
        'external_id' => 'externalId',
        'status' => 'status',
        'disposition_id' => 'dispositionId',
        'disposition_external_id' => 'dispositionExternalId',
        'create_utc' => 'createUtc',
        'update_utc' => 'updateUtc',
        'quick_code_url' => 'quickCodeUrl',
        'attachments' => 'attachments',
        'notes' => 'notes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_number' => 'setItemNumber',
        'serial' => 'setSerial',
        'manufacturer' => 'setManufacturer',
        'country_of_manufacture' => 'setCountryOfManufacture',
        'importer' => 'setImporter',
        'model' => 'setModel',
        'type' => 'setType',
        'caliber' => 'setCaliber',
        'location' => 'setLocation',
        'location_verified_utc' => 'setLocationVerifiedUtc',
        'condition' => 'setCondition',
        'mpn' => 'setMpn',
        'upc' => 'setUpc',
        'sku' => 'setSku',
        'barrel_length' => 'setBarrelLength',
        'overall_length' => 'setOverallLength',
        'acquisition_type' => 'setAcquisitionType',
        'acquire_date' => 'setAcquireDate',
        'acquisition_contact_id' => 'setAcquisitionContactId',
        'acquire_purchase_order_number' => 'setAcquirePurchaseOrderNumber',
        'acquire_invoice_number' => 'setAcquireInvoiceNumber',
        'acquire_shipment_tracking_number' => 'setAcquireShipmentTrackingNumber',
        'disposition_type' => 'setDispositionType',
        'dispose_date' => 'setDisposeDate',
        'disposition_contact_id' => 'setDispositionContactId',
        'dispose_purchase_order_number' => 'setDisposePurchaseOrderNumber',
        'dispose_invoice_number' => 'setDisposeInvoiceNumber',
        'dispose_shipment_tracking_number' => 'setDisposeShipmentTrackingNumber',
        'deleted' => 'setDeleted',
        'disposed' => 'setDisposed',
        'is_theft_loss' => 'setIsTheftLoss',
        'is_destroyed' => 'setIsDestroyed',
        'do_not_dispose' => 'setDoNotDispose',
        'price' => 'setPrice',
        'cost' => 'setCost',
        'id' => 'setId',
        'external_id' => 'setExternalId',
        'status' => 'setStatus',
        'disposition_id' => 'setDispositionId',
        'disposition_external_id' => 'setDispositionExternalId',
        'create_utc' => 'setCreateUtc',
        'update_utc' => 'setUpdateUtc',
        'quick_code_url' => 'setQuickCodeUrl',
        'attachments' => 'setAttachments',
        'notes' => 'setNotes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_number' => 'getItemNumber',
        'serial' => 'getSerial',
        'manufacturer' => 'getManufacturer',
        'country_of_manufacture' => 'getCountryOfManufacture',
        'importer' => 'getImporter',
        'model' => 'getModel',
        'type' => 'getType',
        'caliber' => 'getCaliber',
        'location' => 'getLocation',
        'location_verified_utc' => 'getLocationVerifiedUtc',
        'condition' => 'getCondition',
        'mpn' => 'getMpn',
        'upc' => 'getUpc',
        'sku' => 'getSku',
        'barrel_length' => 'getBarrelLength',
        'overall_length' => 'getOverallLength',
        'acquisition_type' => 'getAcquisitionType',
        'acquire_date' => 'getAcquireDate',
        'acquisition_contact_id' => 'getAcquisitionContactId',
        'acquire_purchase_order_number' => 'getAcquirePurchaseOrderNumber',
        'acquire_invoice_number' => 'getAcquireInvoiceNumber',
        'acquire_shipment_tracking_number' => 'getAcquireShipmentTrackingNumber',
        'disposition_type' => 'getDispositionType',
        'dispose_date' => 'getDisposeDate',
        'disposition_contact_id' => 'getDispositionContactId',
        'dispose_purchase_order_number' => 'getDisposePurchaseOrderNumber',
        'dispose_invoice_number' => 'getDisposeInvoiceNumber',
        'dispose_shipment_tracking_number' => 'getDisposeShipmentTrackingNumber',
        'deleted' => 'getDeleted',
        'disposed' => 'getDisposed',
        'is_theft_loss' => 'getIsTheftLoss',
        'is_destroyed' => 'getIsDestroyed',
        'do_not_dispose' => 'getDoNotDispose',
        'price' => 'getPrice',
        'cost' => 'getCost',
        'id' => 'getId',
        'external_id' => 'getExternalId',
        'status' => 'getStatus',
        'disposition_id' => 'getDispositionId',
        'disposition_external_id' => 'getDispositionExternalId',
        'create_utc' => 'getCreateUtc',
        'update_utc' => 'getUpdateUtc',
        'quick_code_url' => 'getQuickCodeUrl',
        'attachments' => 'getAttachments',
        'notes' => 'getNotes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['item_number'] = isset($data['item_number']) ? $data['item_number'] : null;
        $this->container['serial'] = isset($data['serial']) ? $data['serial'] : null;
        $this->container['manufacturer'] = isset($data['manufacturer']) ? $data['manufacturer'] : null;
        $this->container['country_of_manufacture'] = isset($data['country_of_manufacture']) ? $data['country_of_manufacture'] : null;
        $this->container['importer'] = isset($data['importer']) ? $data['importer'] : null;
        $this->container['model'] = isset($data['model']) ? $data['model'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['caliber'] = isset($data['caliber']) ? $data['caliber'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['location_verified_utc'] = isset($data['location_verified_utc']) ? $data['location_verified_utc'] : null;
        $this->container['condition'] = isset($data['condition']) ? $data['condition'] : null;
        $this->container['mpn'] = isset($data['mpn']) ? $data['mpn'] : null;
        $this->container['upc'] = isset($data['upc']) ? $data['upc'] : null;
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['barrel_length'] = isset($data['barrel_length']) ? $data['barrel_length'] : null;
        $this->container['overall_length'] = isset($data['overall_length']) ? $data['overall_length'] : null;
        $this->container['acquisition_type'] = isset($data['acquisition_type']) ? $data['acquisition_type'] : null;
        $this->container['acquire_date'] = isset($data['acquire_date']) ? $data['acquire_date'] : null;
        $this->container['acquisition_contact_id'] = isset($data['acquisition_contact_id']) ? $data['acquisition_contact_id'] : null;
        $this->container['acquire_purchase_order_number'] = isset($data['acquire_purchase_order_number']) ? $data['acquire_purchase_order_number'] : null;
        $this->container['acquire_invoice_number'] = isset($data['acquire_invoice_number']) ? $data['acquire_invoice_number'] : null;
        $this->container['acquire_shipment_tracking_number'] = isset($data['acquire_shipment_tracking_number']) ? $data['acquire_shipment_tracking_number'] : null;
        $this->container['disposition_type'] = isset($data['disposition_type']) ? $data['disposition_type'] : null;
        $this->container['dispose_date'] = isset($data['dispose_date']) ? $data['dispose_date'] : null;
        $this->container['disposition_contact_id'] = isset($data['disposition_contact_id']) ? $data['disposition_contact_id'] : null;
        $this->container['dispose_purchase_order_number'] = isset($data['dispose_purchase_order_number']) ? $data['dispose_purchase_order_number'] : null;
        $this->container['dispose_invoice_number'] = isset($data['dispose_invoice_number']) ? $data['dispose_invoice_number'] : null;
        $this->container['dispose_shipment_tracking_number'] = isset($data['dispose_shipment_tracking_number']) ? $data['dispose_shipment_tracking_number'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
        $this->container['disposed'] = isset($data['disposed']) ? $data['disposed'] : null;
        $this->container['is_theft_loss'] = isset($data['is_theft_loss']) ? $data['is_theft_loss'] : null;
        $this->container['is_destroyed'] = isset($data['is_destroyed']) ? $data['is_destroyed'] : null;
        $this->container['do_not_dispose'] = isset($data['do_not_dispose']) ? $data['do_not_dispose'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['external_id'] = isset($data['external_id']) ? $data['external_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['disposition_id'] = isset($data['disposition_id']) ? $data['disposition_id'] : null;
        $this->container['disposition_external_id'] = isset($data['disposition_external_id']) ? $data['disposition_external_id'] : null;
        $this->container['create_utc'] = isset($data['create_utc']) ? $data['create_utc'] : null;
        $this->container['update_utc'] = isset($data['update_utc']) ? $data['update_utc'] : null;
        $this->container['quick_code_url'] = isset($data['quick_code_url']) ? $data['quick_code_url'] : null;
        $this->container['attachments'] = isset($data['attachments']) ? $data['attachments'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_number
     *
     * @return string
     */
    public function getItemNumber()
    {
        return $this->container['item_number'];
    }

    /**
     * Sets item_number
     *
     * @param string $item_number item_number
     *
     * @return $this
     */
    public function setItemNumber($item_number)
    {
        $this->container['item_number'] = $item_number;

        return $this;
    }

    /**
     * Gets serial
     *
     * @return string
     */
    public function getSerial()
    {
        return $this->container['serial'];
    }

    /**
     * Sets serial
     *
     * @param string $serial serial
     *
     * @return $this
     */
    public function setSerial($serial)
    {
        $this->container['serial'] = $serial;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string $manufacturer manufacturer
     *
     * @return $this
     */
    public function setManufacturer($manufacturer)
    {
        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets country_of_manufacture
     *
     * @return string
     */
    public function getCountryOfManufacture()
    {
        return $this->container['country_of_manufacture'];
    }

    /**
     * Sets country_of_manufacture
     *
     * @param string $country_of_manufacture country_of_manufacture
     *
     * @return $this
     */
    public function setCountryOfManufacture($country_of_manufacture)
    {
        $this->container['country_of_manufacture'] = $country_of_manufacture;

        return $this;
    }

    /**
     * Gets importer
     *
     * @return string
     */
    public function getImporter()
    {
        return $this->container['importer'];
    }

    /**
     * Sets importer
     *
     * @param string $importer importer
     *
     * @return $this
     */
    public function setImporter($importer)
    {
        $this->container['importer'] = $importer;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string $model model
     *
     * @return $this
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets caliber
     *
     * @return string
     */
    public function getCaliber()
    {
        return $this->container['caliber'];
    }

    /**
     * Sets caliber
     *
     * @param string $caliber caliber
     *
     * @return $this
     */
    public function setCaliber($caliber)
    {
        $this->container['caliber'] = $caliber;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets location_verified_utc
     *
     * @return \DateTime
     */
    public function getLocationVerifiedUtc()
    {
        return $this->container['location_verified_utc'];
    }

    /**
     * Sets location_verified_utc
     *
     * @param \DateTime $location_verified_utc location_verified_utc
     *
     * @return $this
     */
    public function setLocationVerifiedUtc($location_verified_utc)
    {
        $this->container['location_verified_utc'] = $location_verified_utc;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string $condition condition
     *
     * @return $this
     */
    public function setCondition($condition)
    {
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets mpn
     *
     * @return string
     */
    public function getMpn()
    {
        return $this->container['mpn'];
    }

    /**
     * Sets mpn
     *
     * @param string $mpn mpn
     *
     * @return $this
     */
    public function setMpn($mpn)
    {
        $this->container['mpn'] = $mpn;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc upc
     *
     * @return $this
     */
    public function setUpc($upc)
    {
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string $sku sku
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets barrel_length
     *
     * @return double
     */
    public function getBarrelLength()
    {
        return $this->container['barrel_length'];
    }

    /**
     * Sets barrel_length
     *
     * @param double $barrel_length barrel_length
     *
     * @return $this
     */
    public function setBarrelLength($barrel_length)
    {
        $this->container['barrel_length'] = $barrel_length;

        return $this;
    }

    /**
     * Gets overall_length
     *
     * @return double
     */
    public function getOverallLength()
    {
        return $this->container['overall_length'];
    }

    /**
     * Sets overall_length
     *
     * @param double $overall_length overall_length
     *
     * @return $this
     */
    public function setOverallLength($overall_length)
    {
        $this->container['overall_length'] = $overall_length;

        return $this;
    }

    /**
     * Gets acquisition_type
     *
     * @return string
     */
    public function getAcquisitionType()
    {
        return $this->container['acquisition_type'];
    }

    /**
     * Sets acquisition_type
     *
     * @param string $acquisition_type acquisition_type
     *
     * @return $this
     */
    public function setAcquisitionType($acquisition_type)
    {
        $this->container['acquisition_type'] = $acquisition_type;

        return $this;
    }

    /**
     * Gets acquire_date
     *
     * @return \DateTime
     */
    public function getAcquireDate()
    {
        return $this->container['acquire_date'];
    }

    /**
     * Sets acquire_date
     *
     * @param \DateTime $acquire_date acquire_date
     *
     * @return $this
     */
    public function setAcquireDate($acquire_date)
    {
        $this->container['acquire_date'] = $acquire_date;

        return $this;
    }

    /**
     * Gets acquisition_contact_id
     *
     * @return string
     */
    public function getAcquisitionContactId()
    {
        return $this->container['acquisition_contact_id'];
    }

    /**
     * Sets acquisition_contact_id
     *
     * @param string $acquisition_contact_id acquisition_contact_id
     *
     * @return $this
     */
    public function setAcquisitionContactId($acquisition_contact_id)
    {
        $this->container['acquisition_contact_id'] = $acquisition_contact_id;

        return $this;
    }

    /**
     * Gets acquire_purchase_order_number
     *
     * @return string
     */
    public function getAcquirePurchaseOrderNumber()
    {
        return $this->container['acquire_purchase_order_number'];
    }

    /**
     * Sets acquire_purchase_order_number
     *
     * @param string $acquire_purchase_order_number acquire_purchase_order_number
     *
     * @return $this
     */
    public function setAcquirePurchaseOrderNumber($acquire_purchase_order_number)
    {
        $this->container['acquire_purchase_order_number'] = $acquire_purchase_order_number;

        return $this;
    }

    /**
     * Gets acquire_invoice_number
     *
     * @return string
     */
    public function getAcquireInvoiceNumber()
    {
        return $this->container['acquire_invoice_number'];
    }

    /**
     * Sets acquire_invoice_number
     *
     * @param string $acquire_invoice_number acquire_invoice_number
     *
     * @return $this
     */
    public function setAcquireInvoiceNumber($acquire_invoice_number)
    {
        $this->container['acquire_invoice_number'] = $acquire_invoice_number;

        return $this;
    }

    /**
     * Gets acquire_shipment_tracking_number
     *
     * @return string
     */
    public function getAcquireShipmentTrackingNumber()
    {
        return $this->container['acquire_shipment_tracking_number'];
    }

    /**
     * Sets acquire_shipment_tracking_number
     *
     * @param string $acquire_shipment_tracking_number acquire_shipment_tracking_number
     *
     * @return $this
     */
    public function setAcquireShipmentTrackingNumber($acquire_shipment_tracking_number)
    {
        $this->container['acquire_shipment_tracking_number'] = $acquire_shipment_tracking_number;

        return $this;
    }

    /**
     * Gets disposition_type
     *
     * @return string
     */
    public function getDispositionType()
    {
        return $this->container['disposition_type'];
    }

    /**
     * Sets disposition_type
     *
     * @param string $disposition_type disposition_type
     *
     * @return $this
     */
    public function setDispositionType($disposition_type)
    {
        $this->container['disposition_type'] = $disposition_type;

        return $this;
    }

    /**
     * Gets dispose_date
     *
     * @return \DateTime
     */
    public function getDisposeDate()
    {
        return $this->container['dispose_date'];
    }

    /**
     * Sets dispose_date
     *
     * @param \DateTime $dispose_date dispose_date
     *
     * @return $this
     */
    public function setDisposeDate($dispose_date)
    {
        $this->container['dispose_date'] = $dispose_date;

        return $this;
    }

    /**
     * Gets disposition_contact_id
     *
     * @return string
     */
    public function getDispositionContactId()
    {
        return $this->container['disposition_contact_id'];
    }

    /**
     * Sets disposition_contact_id
     *
     * @param string $disposition_contact_id disposition_contact_id
     *
     * @return $this
     */
    public function setDispositionContactId($disposition_contact_id)
    {
        $this->container['disposition_contact_id'] = $disposition_contact_id;

        return $this;
    }

    /**
     * Gets dispose_purchase_order_number
     *
     * @return string
     */
    public function getDisposePurchaseOrderNumber()
    {
        return $this->container['dispose_purchase_order_number'];
    }

    /**
     * Sets dispose_purchase_order_number
     *
     * @param string $dispose_purchase_order_number dispose_purchase_order_number
     *
     * @return $this
     */
    public function setDisposePurchaseOrderNumber($dispose_purchase_order_number)
    {
        $this->container['dispose_purchase_order_number'] = $dispose_purchase_order_number;

        return $this;
    }

    /**
     * Gets dispose_invoice_number
     *
     * @return string
     */
    public function getDisposeInvoiceNumber()
    {
        return $this->container['dispose_invoice_number'];
    }

    /**
     * Sets dispose_invoice_number
     *
     * @param string $dispose_invoice_number dispose_invoice_number
     *
     * @return $this
     */
    public function setDisposeInvoiceNumber($dispose_invoice_number)
    {
        $this->container['dispose_invoice_number'] = $dispose_invoice_number;

        return $this;
    }

    /**
     * Gets dispose_shipment_tracking_number
     *
     * @return string
     */
    public function getDisposeShipmentTrackingNumber()
    {
        return $this->container['dispose_shipment_tracking_number'];
    }

    /**
     * Sets dispose_shipment_tracking_number
     *
     * @param string $dispose_shipment_tracking_number dispose_shipment_tracking_number
     *
     * @return $this
     */
    public function setDisposeShipmentTrackingNumber($dispose_shipment_tracking_number)
    {
        $this->container['dispose_shipment_tracking_number'] = $dispose_shipment_tracking_number;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool $deleted Mapped from Detail.Deleted.
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets disposed
     *
     * @return bool
     */
    public function getDisposed()
    {
        return $this->container['disposed'];
    }

    /**
     * Sets disposed
     *
     * @param bool $disposed True if Detail.Dispose_Date is NOT null; false otherwise.
     *
     * @return $this
     */
    public function setDisposed($disposed)
    {
        $this->container['disposed'] = $disposed;

        return $this;
    }

    /**
     * Gets is_theft_loss
     *
     * @return bool
     */
    public function getIsTheftLoss()
    {
        return $this->container['is_theft_loss'];
    }

    /**
     * Sets is_theft_loss
     *
     * @param bool $is_theft_loss If Disposed and DispositionType == Theft/Loss, true. Otherwise, false.
     *
     * @return $this
     */
    public function setIsTheftLoss($is_theft_loss)
    {
        $this->container['is_theft_loss'] = $is_theft_loss;

        return $this;
    }

    /**
     * Gets is_destroyed
     *
     * @return bool
     */
    public function getIsDestroyed()
    {
        return $this->container['is_destroyed'];
    }

    /**
     * Sets is_destroyed
     *
     * @param bool $is_destroyed If Disposed and DispositionType == Destroyed, true. Otherwise, false.
     *
     * @return $this
     */
    public function setIsDestroyed($is_destroyed)
    {
        $this->container['is_destroyed'] = $is_destroyed;

        return $this;
    }

    /**
     * Gets do_not_dispose
     *
     * @return bool
     */
    public function getDoNotDispose()
    {
        return $this->container['do_not_dispose'];
    }

    /**
     * Sets do_not_dispose
     *
     * @param bool $do_not_dispose do_not_dispose
     *
     * @return $this
     */
    public function setDoNotDispose($do_not_dispose)
    {
        $this->container['do_not_dispose'] = $do_not_dispose;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return double
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param double $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string $external_id external_id
     *
     * @return $this
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemStatusModel $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets disposition_id
     *
     * @return string
     */
    public function getDispositionId()
    {
        return $this->container['disposition_id'];
    }

    /**
     * Sets disposition_id
     *
     * @param string $disposition_id disposition_id
     *
     * @return $this
     */
    public function setDispositionId($disposition_id)
    {
        $this->container['disposition_id'] = $disposition_id;

        return $this;
    }

    /**
     * Gets disposition_external_id
     *
     * @return string
     */
    public function getDispositionExternalId()
    {
        return $this->container['disposition_external_id'];
    }

    /**
     * Sets disposition_external_id
     *
     * @param string $disposition_external_id disposition_external_id
     *
     * @return $this
     */
    public function setDispositionExternalId($disposition_external_id)
    {
        $this->container['disposition_external_id'] = $disposition_external_id;

        return $this;
    }

    /**
     * Gets create_utc
     *
     * @return \DateTime
     */
    public function getCreateUtc()
    {
        return $this->container['create_utc'];
    }

    /**
     * Sets create_utc
     *
     * @param \DateTime $create_utc create_utc
     *
     * @return $this
     */
    public function setCreateUtc($create_utc)
    {
        $this->container['create_utc'] = $create_utc;

        return $this;
    }

    /**
     * Gets update_utc
     *
     * @return \DateTime
     */
    public function getUpdateUtc()
    {
        return $this->container['update_utc'];
    }

    /**
     * Sets update_utc
     *
     * @param \DateTime $update_utc update_utc
     *
     * @return $this
     */
    public function setUpdateUtc($update_utc)
    {
        $this->container['update_utc'] = $update_utc;

        return $this;
    }

    /**
     * Gets quick_code_url
     *
     * @return string
     */
    public function getQuickCodeUrl()
    {
        return $this->container['quick_code_url'];
    }

    /**
     * Sets quick_code_url
     *
     * @param string $quick_code_url quick_code_url
     *
     * @return $this
     */
    public function setQuickCodeUrl($quick_code_url)
    {
        $this->container['quick_code_url'] = $quick_code_url;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[]
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemAttachmentModel[] $attachments attachments
     *
     * @return $this
     */
    public function setAttachments($attachments)
    {
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[]
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param \Swagger\Client\Model\FastBoundWebModelsApiV1ItemsItemNoteModel[] $notes notes
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
