<?php
/**
 * FastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommandTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommand
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommandTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommand"
     */
    public function testFastBoundWebModelsApiV1DispositionsCreateAndCommitDispositionCommand()
    {
    }

    /**
     * Test attribute "request_type"
     */
    public function testPropertyRequestType()
    {
    }

    /**
     * Test attribute "contact_id"
     */
    public function testPropertyContactId()
    {
    }

    /**
     * Test attribute "contact_external_id"
     */
    public function testPropertyContactExternalId()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "manufacturing_changes"
     */
    public function testPropertyManufacturingChanges()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "ttsn"
     */
    public function testPropertyTtsn()
    {
    }

    /**
     * Test attribute "generate_ttsn"
     */
    public function testPropertyGenerateTtsn()
    {
    }

    /**
     * Test attribute "otsn"
     */
    public function testPropertyOtsn()
    {
    }

    /**
     * Test attribute "purchase_order_number"
     */
    public function testPropertyPurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "shipment_tracking_number"
     */
    public function testPropertyShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }

    /**
     * Test attribute "theft_loss_discovered_date"
     */
    public function testPropertyTheftLossDiscoveredDate()
    {
    }

    /**
     * Test attribute "theft_loss_type"
     */
    public function testPropertyTheftLossType()
    {
    }

    /**
     * Test attribute "theft_loss_atf_issued_incident_number"
     */
    public function testPropertyTheftLossAtfIssuedIncidentNumber()
    {
    }

    /**
     * Test attribute "theft_loss_police_incident_number"
     */
    public function testPropertyTheftLossPoliceIncidentNumber()
    {
    }

    /**
     * Test attribute "destroyed_date"
     */
    public function testPropertyDestroyedDate()
    {
    }

    /**
     * Test attribute "destroyed_description"
     */
    public function testPropertyDestroyedDescription()
    {
    }

    /**
     * Test attribute "destroyed_witness1"
     */
    public function testPropertyDestroyedWitness1()
    {
    }

    /**
     * Test attribute "destroyed_witness2"
     */
    public function testPropertyDestroyedWitness2()
    {
    }

    /**
     * Test attribute "other_transferee_emails"
     */
    public function testPropertyOtherTransfereeEmails()
    {
    }
}
