<?php
/**
 * FastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModelTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModel"
     */
    public function testFastBoundWebModelsApiV1DispositionsCommitManufacturingChangesModel()
    {
    }

    /**
     * Test attribute "change_manufacturer"
     */
    public function testPropertyChangeManufacturer()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "change_country_of_manufacture"
     */
    public function testPropertyChangeCountryOfManufacture()
    {
    }

    /**
     * Test attribute "country_of_manufacture"
     */
    public function testPropertyCountryOfManufacture()
    {
    }

    /**
     * Test attribute "change_importer"
     */
    public function testPropertyChangeImporter()
    {
    }

    /**
     * Test attribute "importer"
     */
    public function testPropertyImporter()
    {
    }

    /**
     * Test attribute "change_model"
     */
    public function testPropertyChangeModel()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "change_caliber"
     */
    public function testPropertyChangeCaliber()
    {
    }

    /**
     * Test attribute "caliber"
     */
    public function testPropertyCaliber()
    {
    }

    /**
     * Test attribute "change_type"
     */
    public function testPropertyChangeType()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "change_barrel_length"
     */
    public function testPropertyChangeBarrelLength()
    {
    }

    /**
     * Test attribute "barrel_length"
     */
    public function testPropertyBarrelLength()
    {
    }

    /**
     * Test attribute "change_overall_length"
     */
    public function testPropertyChangeOverallLength()
    {
    }

    /**
     * Test attribute "overall_length"
     */
    public function testPropertyOverallLength()
    {
    }

    /**
     * Test attribute "change_condition"
     */
    public function testPropertyChangeCondition()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "change_cost"
     */
    public function testPropertyChangeCost()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "change_price"
     */
    public function testPropertyChangePrice()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "change_mpn"
     */
    public function testPropertyChangeMpn()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "change_upc"
     */
    public function testPropertyChangeUpc()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "change_sku"
     */
    public function testPropertyChangeSku()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "change_location"
     */
    public function testPropertyChangeLocation()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "change_item_note"
     */
    public function testPropertyChangeItemNote()
    {
    }

    /**
     * Test attribute "item_note"
     */
    public function testPropertyItemNote()
    {
    }
}
