<?php
/**
 * FastBoundWebModelsApiV1DispositionsGetDispositionResponseModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1DispositionsGetDispositionResponseModelTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1DispositionsGetDispositionResponseModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1DispositionsGetDispositionResponseModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1DispositionsGetDispositionResponseModel"
     */
    public function testFastBoundWebModelsApiV1DispositionsGetDispositionResponseModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "purchase_order_number"
     */
    public function testPropertyPurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "shipment_tracking_number"
     */
    public function testPropertyShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "ttsn"
     */
    public function testPropertyTtsn()
    {
    }

    /**
     * Test attribute "otsn"
     */
    public function testPropertyOtsn()
    {
    }

    /**
     * Test attribute "create_user_email"
     */
    public function testPropertyCreateUserEmail()
    {
    }

    /**
     * Test attribute "theft_loss_discovered_date"
     */
    public function testPropertyTheftLossDiscoveredDate()
    {
    }

    /**
     * Test attribute "theft_loss_type"
     */
    public function testPropertyTheftLossType()
    {
    }

    /**
     * Test attribute "theft_loss_atf_issued_incident_number"
     */
    public function testPropertyTheftLossAtfIssuedIncidentNumber()
    {
    }

    /**
     * Test attribute "theft_loss_police_incident_number"
     */
    public function testPropertyTheftLossPoliceIncidentNumber()
    {
    }

    /**
     * Test attribute "destroyed_date"
     */
    public function testPropertyDestroyedDate()
    {
    }

    /**
     * Test attribute "destroyed_description"
     */
    public function testPropertyDestroyedDescription()
    {
    }

    /**
     * Test attribute "destroyed_witness1"
     */
    public function testPropertyDestroyedWitness1()
    {
    }

    /**
     * Test attribute "destroyed_witness2"
     */
    public function testPropertyDestroyedWitness2()
    {
    }

    /**
     * Test attribute "is4473"
     */
    public function testPropertyIs4473()
    {
    }

    /**
     * Test attribute "is_manufacturing_disposition"
     */
    public function testPropertyIsManufacturingDisposition()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "disposed_to_contact"
     */
    public function testPropertyDisposedToContact()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
