<?php
/**
 * FastBoundWebModelsApiV1ContactsCreateContactCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1ContactsCreateContactCommandTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1ContactsCreateContactCommand
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ContactsCreateContactCommandTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1ContactsCreateContactCommand"
     */
    public function testFastBoundWebModelsApiV1ContactsCreateContactCommand()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "ffl_number"
     */
    public function testPropertyFflNumber()
    {
    }

    /**
     * Test attribute "ffl_expires"
     */
    public function testPropertyFflExpires()
    {
    }

    /**
     * Test attribute "lookup_ffl"
     */
    public function testPropertyLookupFfl()
    {
    }

    /**
     * Test attribute "license_name"
     */
    public function testPropertyLicenseName()
    {
    }

    /**
     * Test attribute "trade_name"
     */
    public function testPropertyTradeName()
    {
    }

    /**
     * Test attribute "sotein"
     */
    public function testPropertySotein()
    {
    }

    /**
     * Test attribute "sot_class"
     */
    public function testPropertySotClass()
    {
    }

    /**
     * Test attribute "business_type"
     */
    public function testPropertyBusinessType()
    {
    }

    /**
     * Test attribute "organization_name"
     */
    public function testPropertyOrganizationName()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "premise_address1"
     */
    public function testPropertyPremiseAddress1()
    {
    }

    /**
     * Test attribute "premise_address2"
     */
    public function testPropertyPremiseAddress2()
    {
    }

    /**
     * Test attribute "premise_city"
     */
    public function testPropertyPremiseCity()
    {
    }

    /**
     * Test attribute "premise_county"
     */
    public function testPropertyPremiseCounty()
    {
    }

    /**
     * Test attribute "premise_state"
     */
    public function testPropertyPremiseState()
    {
    }

    /**
     * Test attribute "premise_zip_code"
     */
    public function testPropertyPremiseZipCode()
    {
    }

    /**
     * Test attribute "premise_country"
     */
    public function testPropertyPremiseCountry()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }
}
