<?php
/**
 * FastBoundWebModelsApiV1ItemsEditItemCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1ItemsEditItemCommandTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1ItemsEditItemCommand
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ItemsEditItemCommandTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1ItemsEditItemCommand"
     */
    public function testFastBoundWebModelsApiV1ItemsEditItemCommand()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "do_not_dispose"
     */
    public function testPropertyDoNotDispose()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "importer"
     */
    public function testPropertyImporter()
    {
    }

    /**
     * Test attribute "country_of_manufacture"
     */
    public function testPropertyCountryOfManufacture()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "caliber"
     */
    public function testPropertyCaliber()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "barrel_length"
     */
    public function testPropertyBarrelLength()
    {
    }

    /**
     * Test attribute "total_length"
     */
    public function testPropertyTotalLength()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "location_verified_utc"
     */
    public function testPropertyLocationVerifiedUtc()
    {
    }

    /**
     * Test attribute "acquire_date"
     */
    public function testPropertyAcquireDate()
    {
    }

    /**
     * Test attribute "acquisition_type"
     */
    public function testPropertyAcquisitionType()
    {
    }

    /**
     * Test attribute "acquire_purchase_order_number"
     */
    public function testPropertyAcquirePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "acquire_invoice_number"
     */
    public function testPropertyAcquireInvoiceNumber()
    {
    }

    /**
     * Test attribute "acquire_shipment_tracking_number"
     */
    public function testPropertyAcquireShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "dispose_date"
     */
    public function testPropertyDisposeDate()
    {
    }

    /**
     * Test attribute "disposition_type"
     */
    public function testPropertyDispositionType()
    {
    }

    /**
     * Test attribute "dispose_purchase_order_number"
     */
    public function testPropertyDisposePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "dispose_invoice_number"
     */
    public function testPropertyDisposeInvoiceNumber()
    {
    }

    /**
     * Test attribute "dispose_shipment_tracking_number"
     */
    public function testPropertyDisposeShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "ttsn"
     */
    public function testPropertyTtsn()
    {
    }

    /**
     * Test attribute "otsn"
     */
    public function testPropertyOtsn()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }

    /**
     * Test attribute "theft_loss_discovered_date"
     */
    public function testPropertyTheftLossDiscoveredDate()
    {
    }

    /**
     * Test attribute "theft_loss_type"
     */
    public function testPropertyTheftLossType()
    {
    }

    /**
     * Test attribute "theft_loss_atf_issued_incident_number"
     */
    public function testPropertyTheftLossAtfIssuedIncidentNumber()
    {
    }

    /**
     * Test attribute "theft_loss_police_incident_number"
     */
    public function testPropertyTheftLossPoliceIncidentNumber()
    {
    }

    /**
     * Test attribute "destroyed_date"
     */
    public function testPropertyDestroyedDate()
    {
    }

    /**
     * Test attribute "destroyed_description"
     */
    public function testPropertyDestroyedDescription()
    {
    }

    /**
     * Test attribute "destroyed_witness1"
     */
    public function testPropertyDestroyedWitness1()
    {
    }

    /**
     * Test attribute "destroyed_witness2"
     */
    public function testPropertyDestroyedWitness2()
    {
    }

    /**
     * Test attribute "lightspeed_system_id"
     */
    public function testPropertyLightspeedSystemId()
    {
    }

    /**
     * Test attribute "lightspeed_serial_id"
     */
    public function testPropertyLightspeedSerialId()
    {
    }

    /**
     * Test attribute "lightspeed_sale_id"
     */
    public function testPropertyLightspeedSaleId()
    {
    }
}
