<?php
/**
 * FastBoundWebModelsApiV1ItemsGetItemCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1ItemsGetItemCommandTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1ItemsGetItemCommand
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ItemsGetItemCommandTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1ItemsGetItemCommand"
     */
    public function testFastBoundWebModelsApiV1ItemsGetItemCommand()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "do_not_dispose"
     */
    public function testPropertyDoNotDispose()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "importer"
     */
    public function testPropertyImporter()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "caliber"
     */
    public function testPropertyCaliber()
    {
    }

    /**
     * Test attribute "country_of_manufacture"
     */
    public function testPropertyCountryOfManufacture()
    {
    }

    /**
     * Test attribute "barrel_length"
     */
    public function testPropertyBarrelLength()
    {
    }

    /**
     * Test attribute "overall_length"
     */
    public function testPropertyOverallLength()
    {
    }

    /**
     * Test attribute "total_length"
     */
    public function testPropertyTotalLength()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "location_verified_utc"
     */
    public function testPropertyLocationVerifiedUtc()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "profit"
     */
    public function testPropertyProfit()
    {
    }

    /**
     * Test attribute "margin"
     */
    public function testPropertyMargin()
    {
    }

    /**
     * Test attribute "acquisition_type"
     */
    public function testPropertyAcquisitionType()
    {
    }

    /**
     * Test attribute "acquire_date"
     */
    public function testPropertyAcquireDate()
    {
    }

    /**
     * Test attribute "acquisition_user_email"
     */
    public function testPropertyAcquisitionUserEmail()
    {
    }

    /**
     * Test attribute "acquire_purchase_order_number"
     */
    public function testPropertyAcquirePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "acquire_invoice_number"
     */
    public function testPropertyAcquireInvoiceNumber()
    {
    }

    /**
     * Test attribute "acquire_shipment_tracking_number"
     */
    public function testPropertyAcquireShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "acquire_license"
     */
    public function testPropertyAcquireLicense()
    {
    }

    /**
     * Test attribute "acquire_license_name"
     */
    public function testPropertyAcquireLicenseName()
    {
    }

    /**
     * Test attribute "acquire_license_expires"
     */
    public function testPropertyAcquireLicenseExpires()
    {
    }

    /**
     * Test attribute "acquire_organization"
     */
    public function testPropertyAcquireOrganization()
    {
    }

    /**
     * Test attribute "acquire_first_name"
     */
    public function testPropertyAcquireFirstName()
    {
    }

    /**
     * Test attribute "acquire_last_name"
     */
    public function testPropertyAcquireLastName()
    {
    }

    /**
     * Test attribute "acquire_address1"
     */
    public function testPropertyAcquireAddress1()
    {
    }

    /**
     * Test attribute "acquire_address2"
     */
    public function testPropertyAcquireAddress2()
    {
    }

    /**
     * Test attribute "acquire_city"
     */
    public function testPropertyAcquireCity()
    {
    }

    /**
     * Test attribute "acquire_state"
     */
    public function testPropertyAcquireState()
    {
    }

    /**
     * Test attribute "acquire_postal"
     */
    public function testPropertyAcquirePostal()
    {
    }

    /**
     * Test attribute "acquire_country"
     */
    public function testPropertyAcquireCountry()
    {
    }

    /**
     * Test attribute "acquire_phone_number"
     */
    public function testPropertyAcquirePhoneNumber()
    {
    }

    /**
     * Test attribute "acquire_fax"
     */
    public function testPropertyAcquireFax()
    {
    }

    /**
     * Test attribute "acquire_email_address"
     */
    public function testPropertyAcquireEmailAddress()
    {
    }

    /**
     * Test attribute "disposition_type"
     */
    public function testPropertyDispositionType()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "dispose_date"
     */
    public function testPropertyDisposeDate()
    {
    }

    /**
     * Test attribute "ttsn"
     */
    public function testPropertyTtsn()
    {
    }

    /**
     * Test attribute "otsn"
     */
    public function testPropertyOtsn()
    {
    }

    /**
     * Test attribute "disposition_user_email"
     */
    public function testPropertyDispositionUserEmail()
    {
    }

    /**
     * Test attribute "dispose_purchase_order_number"
     */
    public function testPropertyDisposePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "dispose_invoice_number"
     */
    public function testPropertyDisposeInvoiceNumber()
    {
    }

    /**
     * Test attribute "dispose_shipment_tracking_number"
     */
    public function testPropertyDisposeShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "dispose_license"
     */
    public function testPropertyDisposeLicense()
    {
    }

    /**
     * Test attribute "dispose_license_name"
     */
    public function testPropertyDisposeLicenseName()
    {
    }

    /**
     * Test attribute "dispose_license_expires"
     */
    public function testPropertyDisposeLicenseExpires()
    {
    }

    /**
     * Test attribute "dispose_organization"
     */
    public function testPropertyDisposeOrganization()
    {
    }

    /**
     * Test attribute "dispose_first_name"
     */
    public function testPropertyDisposeFirstName()
    {
    }

    /**
     * Test attribute "dispose_last_name"
     */
    public function testPropertyDisposeLastName()
    {
    }

    /**
     * Test attribute "dispose_address1"
     */
    public function testPropertyDisposeAddress1()
    {
    }

    /**
     * Test attribute "dispose_address2"
     */
    public function testPropertyDisposeAddress2()
    {
    }

    /**
     * Test attribute "dispose_city"
     */
    public function testPropertyDisposeCity()
    {
    }

    /**
     * Test attribute "dispose_state"
     */
    public function testPropertyDisposeState()
    {
    }

    /**
     * Test attribute "dispose_postal"
     */
    public function testPropertyDisposePostal()
    {
    }

    /**
     * Test attribute "dispose_country"
     */
    public function testPropertyDisposeCountry()
    {
    }

    /**
     * Test attribute "dispose_phone_number"
     */
    public function testPropertyDisposePhoneNumber()
    {
    }

    /**
     * Test attribute "dispose_fax"
     */
    public function testPropertyDisposeFax()
    {
    }

    /**
     * Test attribute "dispose_email_address"
     */
    public function testPropertyDisposeEmailAddress()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }

    /**
     * Test attribute "theft_loss_discovered_date"
     */
    public function testPropertyTheftLossDiscoveredDate()
    {
    }

    /**
     * Test attribute "theft_loss_type"
     */
    public function testPropertyTheftLossType()
    {
    }

    /**
     * Test attribute "theft_loss_atf_issued_incident_number"
     */
    public function testPropertyTheftLossAtfIssuedIncidentNumber()
    {
    }

    /**
     * Test attribute "theft_loss_police_incident_number"
     */
    public function testPropertyTheftLossPoliceIncidentNumber()
    {
    }

    /**
     * Test attribute "destroyed_date"
     */
    public function testPropertyDestroyedDate()
    {
    }

    /**
     * Test attribute "destroyed_description"
     */
    public function testPropertyDestroyedDescription()
    {
    }

    /**
     * Test attribute "destroyed_witness1"
     */
    public function testPropertyDestroyedWitness1()
    {
    }

    /**
     * Test attribute "destroyed_witness2"
     */
    public function testPropertyDestroyedWitness2()
    {
    }

    /**
     * Test attribute "multiple_sale_reports"
     */
    public function testPropertyMultipleSaleReports()
    {
    }

    /**
     * Test attribute "lightspeed_system_id"
     */
    public function testPropertyLightspeedSystemId()
    {
    }

    /**
     * Test attribute "lightspeed_serial_id"
     */
    public function testPropertyLightspeedSerialId()
    {
    }

    /**
     * Test attribute "lightspeed_sale_id"
     */
    public function testPropertyLightspeedSaleId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "disposition_id"
     */
    public function testPropertyDispositionId()
    {
    }

    /**
     * Test attribute "disposition_external_id"
     */
    public function testPropertyDispositionExternalId()
    {
    }

    /**
     * Test attribute "create_utc"
     */
    public function testPropertyCreateUtc()
    {
    }

    /**
     * Test attribute "update_utc"
     */
    public function testPropertyUpdateUtc()
    {
    }

    /**
     * Test attribute "quick_code_url"
     */
    public function testPropertyQuickCodeUrl()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }
}
