<?php
/**
 * FastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModelTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModel"
     */
    public function testFastBoundWebModelsApiV1DownloadsBoundBookDownloadDetailsModel()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "file_size_in_bytes"
     */
    public function testPropertyFileSizeInBytes()
    {
    }

    /**
     * Test attribute "url_expires_on_seconds"
     */
    public function testPropertyUrlExpiresOnSeconds()
    {
    }
}
