<?php
/**
 * FastBoundWebModelsApiV1DispositionsGetAll4473CommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1DispositionsGetAll4473CommandTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1DispositionsGetAll4473Command
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1DispositionsGetAll4473CommandTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1DispositionsGetAll4473Command"
     */
    public function testFastBoundWebModelsApiV1DispositionsGetAll4473Command()
    {
    }

    /**
     * Test attribute "dispositions"
     */
    public function testPropertyDispositions()
    {
    }

    /**
     * Test attribute "records"
     */
    public function testPropertyRecords()
    {
    }
}
