<?php
/**
 * FastBoundWebModelsApiV1ItemsGetAllCommandItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FastBoundWebModelsApiV1ItemsGetAllCommandItemTest Class Doc Comment
 *
 * @category    Class
 * @description FastBoundWebModelsApiV1ItemsGetAllCommandItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FastBoundWebModelsApiV1ItemsGetAllCommandItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FastBoundWebModelsApiV1ItemsGetAllCommandItem"
     */
    public function testFastBoundWebModelsApiV1ItemsGetAllCommandItem()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "country_of_manufacture"
     */
    public function testPropertyCountryOfManufacture()
    {
    }

    /**
     * Test attribute "importer"
     */
    public function testPropertyImporter()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "caliber"
     */
    public function testPropertyCaliber()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "location_verified_utc"
     */
    public function testPropertyLocationVerifiedUtc()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "barrel_length"
     */
    public function testPropertyBarrelLength()
    {
    }

    /**
     * Test attribute "overall_length"
     */
    public function testPropertyOverallLength()
    {
    }

    /**
     * Test attribute "acquisition_type"
     */
    public function testPropertyAcquisitionType()
    {
    }

    /**
     * Test attribute "acquire_date"
     */
    public function testPropertyAcquireDate()
    {
    }

    /**
     * Test attribute "acquisition_contact_id"
     */
    public function testPropertyAcquisitionContactId()
    {
    }

    /**
     * Test attribute "acquire_purchase_order_number"
     */
    public function testPropertyAcquirePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "acquire_invoice_number"
     */
    public function testPropertyAcquireInvoiceNumber()
    {
    }

    /**
     * Test attribute "acquire_shipment_tracking_number"
     */
    public function testPropertyAcquireShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "disposition_type"
     */
    public function testPropertyDispositionType()
    {
    }

    /**
     * Test attribute "dispose_date"
     */
    public function testPropertyDisposeDate()
    {
    }

    /**
     * Test attribute "disposition_contact_id"
     */
    public function testPropertyDispositionContactId()
    {
    }

    /**
     * Test attribute "dispose_purchase_order_number"
     */
    public function testPropertyDisposePurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "dispose_invoice_number"
     */
    public function testPropertyDisposeInvoiceNumber()
    {
    }

    /**
     * Test attribute "dispose_shipment_tracking_number"
     */
    public function testPropertyDisposeShipmentTrackingNumber()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "disposed"
     */
    public function testPropertyDisposed()
    {
    }

    /**
     * Test attribute "is_theft_loss"
     */
    public function testPropertyIsTheftLoss()
    {
    }

    /**
     * Test attribute "is_destroyed"
     */
    public function testPropertyIsDestroyed()
    {
    }

    /**
     * Test attribute "do_not_dispose"
     */
    public function testPropertyDoNotDispose()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "disposition_id"
     */
    public function testPropertyDispositionId()
    {
    }

    /**
     * Test attribute "disposition_external_id"
     */
    public function testPropertyDispositionExternalId()
    {
    }

    /**
     * Test attribute "create_utc"
     */
    public function testPropertyCreateUtc()
    {
    }

    /**
     * Test attribute "update_utc"
     */
    public function testPropertyUpdateUtc()
    {
    }

    /**
     * Test attribute "quick_code_url"
     */
    public function testPropertyQuickCodeUrl()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }
}
