<?php
/**
 * AcquisitionsV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AcquisitionsV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AcquisitionsV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsAcquisitionExternalIdGet
     *
     * Retrieves an acquisition by external ID..
     *
     */
    public function testAccountNumApiAcquisitionsAcquisitionExternalIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsAcquisitionExternalIdItemsAcquisitionItemExternalIdGet
     *
     * Retrieves an item by external ID..
     *
     */
    public function testAccountNumApiAcquisitionsAcquisitionExternalIdItemsAcquisitionItemExternalIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsCreateAndCommitPost
     *
     * Create and commit an acquisition in a single request..
     *
     */
    public function testAccountNumApiAcquisitionsCreateAndCommitPost()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsExternalIdItemsAcquisitionItemIdGet
     *
     * Retrieves an item by ID and the acquisition's external ID..
     *
     */
    public function testAccountNumApiAcquisitionsExternalIdItemsAcquisitionItemIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsGet
     *
     * Retrieves the account's acquisitions..
     *
     */
    public function testAccountNumApiAcquisitionsGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsGetByExternalIdAcquisitionExternalIdGet
     *
     * Retrieves an acquisition by external ID..
     *
     */
    public function testAccountNumApiAcquisitionsGetByExternalIdAcquisitionExternalIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdAttachContactContactIdPut
     *
     * Attaches a contact to an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdAttachContactContactIdPut()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdCommitPost
     *
     * Commits an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdCommitPost()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdDelete
     *
     * Deletes an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdDelete()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdGet
     *
     * Retrieves an acquisition by ID..
     *
     */
    public function testAccountNumApiAcquisitionsIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdItemsAcquisitionItemIdDelete
     *
     * Deletes an item from an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdItemsAcquisitionItemIdDelete()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdItemsAcquisitionItemIdGet
     *
     * Retrieves an item by ID..
     *
     */
    public function testAccountNumApiAcquisitionsIdItemsAcquisitionItemIdGet()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdItemsAcquisitionItemIdPut
     *
     * Edits an item for an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdItemsAcquisitionItemIdPut()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdItemsMultiplePost
     *
     * Add multiple items to an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdItemsMultiplePost()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdItemsPost
     *
     * Creates a new item for an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdItemsPost()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsIdPut
     *
     * Edits an acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsIdPut()
    {
    }

    /**
     * Test case for accountNumApiAcquisitionsPost
     *
     * Creates a new acquisition..
     *
     */
    public function testAccountNumApiAcquisitionsPost()
    {
    }
}
