<?php
/**
 * ItemsV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FastBound API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for accountNumApiItemsExternalIdGet
     *
     * Retrieves the specified item by External ID..
     *
     */
    public function testAccountNumApiItemsExternalIdGet()
    {
    }

    /**
     * Test case for accountNumApiItemsGet
     *
     * Retrieves the account's items..
     *
     */
    public function testAccountNumApiItemsGet()
    {
    }

    /**
     * Test case for accountNumApiItemsGetByExternalIdExternalIdGet
     *
     * Retrieves the specified item by External ID..
     *
     */
    public function testAccountNumApiItemsGetByExternalIdExternalIdGet()
    {
    }

    /**
     * Test case for accountNumApiItemsIdAcquisitionContactContactIdPut
     *
     * Change an item's acquisition contact..
     *
     */
    public function testAccountNumApiItemsIdAcquisitionContactContactIdPut()
    {
    }

    /**
     * Test case for accountNumApiItemsIdDelete
     *
     * Deletes the specified item..
     *
     */
    public function testAccountNumApiItemsIdDelete()
    {
    }

    /**
     * Test case for accountNumApiItemsIdGet
     *
     * Retrieves the specified item by unique ID..
     *
     */
    public function testAccountNumApiItemsIdGet()
    {
    }

    /**
     * Test case for accountNumApiItemsIdPut
     *
     * Edits the specified item..
     *
     */
    public function testAccountNumApiItemsIdPut()
    {
    }

    /**
     * Test case for accountNumApiItemsIdSetExternalIdPut
     *
     * Sets the ExternalId of the specified item..
     *
     */
    public function testAccountNumApiItemsIdSetExternalIdPut()
    {
    }

    /**
     * Test case for accountNumApiItemsIdUndisposePut
     *
     * Undisposes the specified item..
     *
     */
    public function testAccountNumApiItemsIdUndisposePut()
    {
    }

    /**
     * Test case for accountNumApiItemsSetExternalIdsPut
     *
     * Sets the ExternalId of each of the specified items..
     *
     */
    public function testAccountNumApiItemsSetExternalIdsPut()
    {
    }
}
